name: safenexus_hse
description: "AI-Powered HSE Safety & Observation App for UAE"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  http: ^1.5.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
