name: safenexus_hse
description: "AI-Powered HSE Safety & Observation App for UAE"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Image capture / selection
  image_picker: ^1.1.2

  # Local app data
  shared_preferences: ^2.5.3

  # API / AI communication
  http: ^1.5.0

  # File storage
  path_provider: ^2.1.5

  # Share generated PDF / files
  share_plus: ^10.1.4

  # PDF generation
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
