pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "safenexus_hse"

include ":app"

def flutterSdkPath = System.getenv("FLUTTER_ROOT")

if (flutterSdkPath == null) {
    throw new GradleException(
        "FLUTTER_ROOT is not set. Flutter SDK could not be found."
    )
}

apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
