/// SafeNexus HSE — Abu Dhabi Scaffolding Gold Standard content.
/// Regulatory baseline: ADOSH-SF CoP 26.0 — Scaffolding, Version 4.1, February 2026.
/// This is a field-reference layer. The official ADPHC publication remains the
/// controlling source for regulatory compliance decisions.
///
/// 38-section structure locked for SafeNexus HSE Gold Standard topics.

class ScaffoldingGoldPoint {
  final String clause;
  final String title;
  final String meaning;
  final String hazards;
  final String controls;
  final String fieldCheck;
  final String commonMistake;
  final String action;
  final String records;
  final String fieldProcedure;
  final String roles;
  final String preWork;
  final String duringWork;
  final String monitoring;
  final String emergency;
  final String stopWork;
  final String checklist;
  final String interview;

  const ScaffoldingGoldPoint({
    required this.clause,
    required this.title,
    required this.meaning,
    required this.hazards,
    required this.controls,
    required this.fieldCheck,
    required this.commonMistake,
    required this.action,
    required this.records,
    this.fieldProcedure = '',
    this.roles = '',
    this.preWork = '',
    this.duringWork = '',
    this.monitoring = '',
    this.emergency = '',
    this.stopWork = '',
    this.checklist = '',
    this.interview = '',
  });
}

class ScaffoldingGoldSection {
  final String number;
  final String title;
  final String introduction;
  final ScaffoldingGoldPoint point;

  const ScaffoldingGoldSection({
    required this.number,
    required this.title,
    required this.introduction,
    required this.point,
  });
}

const List<ScaffoldingGoldSection> scaffoldingGoldStandardSections = [
  ScaffoldingGoldSection(
    number: '01',
    title: 'Definition & Purpose',
    introduction: 'Define scaffolding as a temporary access/working system and control it from design through dismantling.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 01',
      title: 'Definition & Purpose',
      meaning: 'Define scaffolding as a temporary access/working system and control it from design through dismantling.',
      hazards: 'Scaffold collapse, falls, falling objects, overloading and unsafe access can cause serious injury.',
      controls: 'Use competent design/planning, suitable components, competent erection, inspection, supervision and controlled alteration/dismantling.',
      fieldCheck: 'Confirm scaffold type, purpose, location, height and intended users before erection.',
      commonMistake: 'Treating a scaffold as ordinary site access without design or inspection.',
      action: 'Stop use until the scaffold is correctly assessed and controlled.',
      records: 'Design/plan, RAMS, inspection records, training records.',
      fieldProcedure: 'Define the scaffold as a temporary structure for access and/or work at height. The control lifecycle runs from need identification and design through erection, handover, use, alteration, inspection and dismantling.',
      roles: 'Client/project management establishes the need and resources; designer determines the design basis; competent scaffolders erect/alter; competent inspector verifies; supervisors control use; users report defects.',
      preWork: 'Confirm purpose, height/configuration, expected loads, location, interfaces, access method and whether a standard system or designed scaffold is required.',
      duringWork: 'Use only the approved configuration; protect the structure from unauthorized alteration and uncontrolled loading.',
      monitoring: 'Verify configuration against the approved drawing/system and current inspection status.',
      emergency: 'Plan rescue for falls, collapse and access emergencies before work starts.',
      stopWork: 'Stop if the scaffold purpose, design basis or responsible competent persons are unclear.',
      checklist: 'Purpose/design confirmed; competent persons assigned; foundation and interfaces assessed; handover/inspection process defined.',
      interview: 'What is the difference between erection, alteration, inspection and handover responsibilities?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '02',
    title: 'Scope & Applications',
    introduction: 'Apply the controls to fixed, mobile, tower, suspended and special scaffold arrangements within the applicable scope.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 02',
      title: 'Scope & Applications',
      meaning: 'Apply the controls to fixed, mobile, tower, suspended and special scaffold arrangements within the applicable scope.',
      hazards: 'Different scaffold systems have different stability, loading, access and rescue hazards.',
      controls: 'Identify the system and all applicable Abu Dhabi requirements before work.',
      fieldCheck: 'Check the actual scaffold against the approved system and intended application.',
      commonMistake: 'Mixing components or using a system outside its intended configuration.',
      action: 'Quarantine non-compliant arrangements and obtain competent review.',
      records: 'Scaffold plan, manufacturer information, approval/design records.',
      fieldProcedure: 'Apply the controls to fixed, tube-and-coupler, modular/system, mobile/tower, suspended, cantilever, birdcage and special/designed arrangements as applicable.',
      roles: 'Select the system based on task, geometry, load, height, access, environment and manufacturer/system requirements.',
      preWork: 'Identify the exact scaffold system before procurement or erection; do not assume components are interchangeable.',
      duringWork: 'Keep the installed arrangement within the approved system and control changes through competent review.',
      monitoring: 'Check type, configuration, components and intended use during inspection.',
      emergency: 'Emergency arrangements must reflect the actual scaffold type and access route.',
      stopWork: 'Stop when the installed system does not match the approved design/system.',
      checklist: 'System identified; manufacturer information available; compatibility confirmed; application suitable.',
      interview: 'Why must scaffold type be identified before erection?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '03',
    title: 'Types of Scaffolding',
    introduction: 'Select the scaffold type according to task, height, loading, access and site constraints.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 03',
      title: 'Types of Scaffolding',
      meaning: 'Select the scaffold type according to task, height, loading, access and site constraints.',
      hazards: 'Incorrect type can create instability, excessive loading or unsafe access.',
      controls: 'Assess fixed/tube-and-coupler, modular, mobile/tower, suspended and special arrangements as applicable.',
      fieldCheck: 'Verify the installed configuration matches the planned type.',
      commonMistake: 'Using a mobile tower where a fixed scaffold or engineered solution is required.',
      action: 'Stop and select an appropriate system.',
      records: 'Design/drawing, RAMS, equipment records.',
      fieldProcedure: 'Types must be selected for the task and designed application. Tube-and-coupler, modular/system, mobile/tower, suspended, cantilever, birdcage and special/designed scaffolds have different stability, access, loading and inspection requirements.',
      roles: 'Designer/supervisor selects the system; competent scaffolders follow the approved configuration; users do not convert one system into another.',
      preWork: 'Confirm task, working level, loading, access, base conditions and interfaces before selecting the type.',
      duringWork: 'Do not mix systems or create improvised configurations unless the arrangement is specifically approved/designed.',
      monitoring: 'Verify type, components, bracing, ties, access and load information against the approved basis.',
      emergency: 'Rescue route and isolation method must suit the scaffold type, especially suspended or special arrangements.',
      stopWork: 'Stop for an improvised conversion, incompatible components, missing design information or unsafe stability.',
      checklist: 'Type identified; design basis available; components compatible; access and rescue planned.',
      interview: 'Name the main scaffold types and one key limitation/control for each.',
    ),
  ),
  ScaffoldingGoldSection(
    number: '04',
    title: 'Components / Parts',
    introduction: 'Understand standards, ledgers, transoms, base plates, sole boards, braces, ties, couplers, platforms and edge protection.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 04',
      title: 'Components / Parts',
      meaning: 'Understand standards, ledgers, transoms, base plates, sole boards, braces, ties, couplers, platforms and edge protection.',
      hazards: 'Missing, incompatible or damaged components can weaken the structure.',
      controls: 'Use compatible approved components and install them according to design/manufacturer requirements.',
      fieldCheck: 'Visually trace critical load paths and connections during inspection.',
      commonMistake: 'Substituting components without approval.',
      action: 'Remove defective or incompatible components from service.',
      records: 'Component inspection and manufacturer records.',
      fieldProcedure: 'Critical components include standards/uprights, ledgers, transoms, braces, base plates, sole boards, ties, couplers, platforms, guardrails, toe boards and access components.',
      roles: 'Competent persons must understand the load path and function of each component.',
      preWork: 'Check component condition, compatibility, manufacturer/system requirements and identification before use.',
      duringWork: 'Keep structural and edge-protection components complete; do not substitute damaged or incompatible parts.',
      monitoring: 'Inspect load-bearing members, connections, platforms and edge protection from foundation upward.',
      emergency: 'Secure or isolate loose components after damage or impact; keep people below protected.',
      stopWork: 'Stop for cracked, bent, corroded, damaged, incompatible or missing critical components.',
      checklist: 'Component condition; compatibility; connections; platform; edge protection; access.',
      interview: 'Why is component compatibility important in a scaffold system?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '05',
    title: 'Planning & Design',
    introduction: 'Plan foundation, geometry, ties, loading, access, environmental loads and interfaces before erection.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 05',
      title: 'Planning & Design',
      meaning: 'Plan foundation, geometry, ties, loading, access, environmental loads and interfaces before erection.',
      hazards: 'Unplanned loading, wind, sheeting, cantilevers and unusual configurations can affect stability.',
      controls: 'Use competent engineering/design where required and account for actual site conditions.',
      fieldCheck: 'Compare erection to current approved drawing.',
      commonMistake: 'Building from memory or an old drawing.',
      action: 'Stop erection and obtain the correct design information.',
      records: 'Approved drawing, calculations where required, RAMS.',
      fieldProcedure: 'Design should address intended loads, geometry, foundation, stability, ties/bracing, access, environmental exposure and interfaces.',
      roles: 'Designer/engineer establishes the design basis; project team controls revisions; scaffolders build to the approved information.',
      preWork: 'Use the current approved drawing/calculation/system instructions and confirm site conditions before erection.',
      duringWork: 'No field improvisation of critical structural elements; changes require competent review and controlled revision.',
      monitoring: 'Compare erected geometry and stability arrangements with the current approved basis.',
      emergency: 'Emergency plans must account for the designed access and possible isolation of the scaffold.',
      stopWork: 'Stop when drawings are missing, obsolete, contradictory or site conditions differ materially from the design.',
      checklist: 'Current drawing; design basis; load/use assumptions; revision control; interface review.',
      interview: 'What site changes can require a scaffold design review?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '06',
    title: 'Site Assessment',
    introduction: 'Assess ground, overhead services, adjacent structures, traffic, public areas, weather and nearby work.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 06',
      title: 'Site Assessment',
      meaning: 'Assess ground, overhead services, adjacent structures, traffic, public areas, weather and nearby work.',
      hazards: 'Soft ground, excavation edges, traffic and services can compromise scaffold stability or expose workers.',
      controls: 'Provide suitable foundation, exclusion zones, service controls and interface arrangements.',
      fieldCheck: 'Inspect the full scaffold footprint and surroundings.',
      commonMistake: 'Erecting directly beside an excavation without assessing edge stability.',
      action: 'Reposition or engineer the arrangement before erection.',
      records: 'Site survey, permits/NOCs, risk assessment.',
      fieldProcedure: 'Assess ground, excavation edges, overhead services, adjacent structures, traffic, public interfaces, weather exposure and simultaneous work.',
      roles: 'Site management coordinates interfaces; HSE verifies critical controls; competent persons assess scaffold-specific conditions.',
      preWork: 'Survey the footprint and surrounding area before erection and after significant site changes.',
      duringWork: 'Use exclusion zones, service controls, suitable foundations and interface barriers where required.',
      monitoring: 'Walk the full footprint and surrounding envelope, not only the platform.',
      emergency: 'Maintain emergency access and ensure the scaffold does not block emergency routes.',
      stopWork: 'Stop for unstable ground, uncontrolled traffic/service exposure or unresolved interface hazards.',
      checklist: 'Ground; excavation edge; services; traffic; public; weather; access; nearby work.',
      interview: 'Why can a scaffold beside an excavation require additional assessment?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '07',
    title: 'Foundation / Sole Boards',
    introduction: 'Provide a stable foundation capable of supporting the scaffold and imposed loads.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 07',
      title: 'Foundation / Sole Boards',
      meaning: 'Provide a stable foundation capable of supporting the scaffold and imposed loads.',
      hazards: 'Settlement or uneven bearing can cause leaning, movement or collapse.',
      controls: 'Use suitable sole boards/base arrangements and comply with the applicable CoP/design.',
      fieldCheck: 'Check bearing surface, sole boards, base plates and level.',
      commonMistake: 'Placing standards on loose fill, debris or unsupported covers.',
      action: 'Stop erection until a suitable foundation is provided.',
      records: 'Foundation inspection, scaffold checklist.',
      fieldProcedure: 'The foundation transfers scaffold loads to the supporting ground/structure. Sole boards and base arrangements must be suitable for the design and site conditions.',
      roles: 'Competent persons verify the bearing arrangement; supervision prevents later disturbance.',
      preWork: 'Confirm ground condition, bearing arrangement, level and protection from water/erosion or excavation influence.',
      duringWork: 'Never rely on loose debris, unsupported covers or unassessed surfaces.',
      monitoring: 'Check settlement, movement, level, base plates and sole-board condition.',
      emergency: 'If movement occurs, isolate the scaffold and protect people from collapse exposure.',
      stopWork: 'Stop for settlement, undermining, damaged base components or inadequate bearing.',
      checklist: 'Foundation stable; bases seated; sole boards suitable; no undermining; level maintained.',
      interview: 'What signs indicate that a scaffold foundation may be failing?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '08',
    title: 'Erection Sequence',
    introduction: 'Erect progressively with stability maintained at every stage.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 08',
      title: 'Erection Sequence',
      meaning: 'Erect progressively with stability maintained at every stage.',
      hazards: 'Partially erected scaffolds can be unstable and create fall hazards.',
      controls: 'Follow the approved erection method, maintain bracing/ties progressively and establish an exclusion zone.',
      fieldCheck: 'Confirm every completed lift is stable before progressing.',
      commonMistake: 'Removing braces or ties temporarily without a controlled sequence.',
      action: 'Stop erection and restore the designed stability.',
      records: 'RAMS, erection checklist, competent-person records.',
      fieldProcedure: 'Erect progressively so stability, access and fall protection are maintained at each stage.',
      roles: 'Only competent scaffolders perform erection; a supervisor controls sequence and exclusion zones.',
      preWork: 'Review RAMS, weather, components, foundation and exclusion zone before starting.',
      duringWork: 'Maintain progressive bracing/ties and safe access; never leave a partially erected scaffold uncontrolled.',
      monitoring: 'Inspect each completed stage before advancing where the method requires verification.',
      emergency: 'Plan rescue for a fall during erection and keep emergency access clear.',
      stopWork: 'Stop for missing stability controls, uncontrolled public/traffic exposure or unsafe erection conditions.',
      checklist: 'Sequence understood; exclusion zone; stability maintained; access/fall controls; competent team.',
      interview: 'Why must stability be maintained progressively during erection?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '09',
    title: 'Hazards — One by One',
    introduction: 'Treat collapse, falls, falling objects, overloading, electrical contact, weather and unsafe modification as separate hazards.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 09',
      title: 'Hazards — One by One',
      meaning: 'Treat collapse, falls, falling objects, overloading, electrical contact, weather and unsafe modification as separate hazards.',
      hazards: 'Multiple simultaneous failures can escalate a scaffold incident.',
      controls: 'Identify each hazard and assign a specific control rather than relying only on PPE.',
      fieldCheck: 'Ask: what can fail, who is exposed, and what prevents the failure?',
      commonMistake: 'Using one generic \'scaffold safe\' statement.',
      action: 'Record and control each significant hazard.',
      records: 'Risk assessment/JSA and inspection records.',
      fieldProcedure: 'Treat collapse, falls, falling objects, overloading, electrical contact, weather, unsafe access and unauthorized modification as separate hazards.',
      roles: 'The supervisor and HSE should identify who is exposed and what critical control prevents each event.',
      preWork: 'Use a task-specific risk assessment/JSA rather than a generic scaffold statement.',
      duringWork: 'Assign a physical or procedural control to each significant hazard and verify it in the field.',
      monitoring: 'Walk the scaffold and its surroundings to identify hazards at every level.',
      emergency: 'Emergency scenarios should cover the credible major hazards identified in the assessment.',
      stopWork: 'Stop where a critical hazard has no effective control.',
      checklist: 'Hazard list; exposed persons; controls; owner; verification method.',
      interview: 'Give three separate scaffold hazards and their corresponding controls.',
    ),
  ),
  ScaffoldingGoldSection(
    number: '10',
    title: 'Hazard Identification',
    introduction: 'Identify defects, movement, missing components, inadequate ties, gaps, access issues and interface hazards.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 10',
      title: 'Hazard Identification',
      meaning: 'Identify defects, movement, missing components, inadequate ties, gaps, access issues and interface hazards.',
      hazards: 'Defects can be hidden until loading or weather occurs.',
      controls: 'Use systematic inspections from foundation to highest working level.',
      fieldCheck: 'Walk the complete scaffold and inspect critical connections.',
      commonMistake: 'Inspecting only the platform where workers stand.',
      action: 'Tag/isolated the scaffold when a critical defect is found.',
      records: 'Inspection checklist, photographs, defect log.',
      fieldProcedure: 'Use a systematic inspection from foundation to highest level and include the surrounding interface.',
      roles: 'Inspector identifies defects; supervisor controls access; users report changes or damage.',
      preWork: 'Inspect after erection/handover and after events or alterations requiring reinspection under the applicable system.',
      duringWork: 'Use status identification/tagging only as part of the control system, not as a substitute for inspection.',
      monitoring: 'Check structure, connections, ties, bracing, platforms, edge protection, access, loading and environment.',
      emergency: 'Isolate the scaffold when a critical defect creates immediate danger.',
      stopWork: 'Stop for structural movement, missing critical components, unsafe access or failed edge protection.',
      checklist: 'Foundation-to-top inspection; status; defects; photographs where appropriate; closure.',
      interview: 'What is the difference between checking a tag and conducting an inspection?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '11',
    title: 'Causes',
    introduction: 'Understand failures caused by poor design, poor erection, unauthorized alteration, overloading, weak ground and environmental effects.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 11',
      title: 'Causes',
      meaning: 'Understand failures caused by poor design, poor erection, unauthorized alteration, overloading, weak ground and environmental effects.',
      hazards: 'Failure to address root causes allows recurrence.',
      controls: 'Use competent planning, supervision, inspection and change control.',
      fieldCheck: 'Look for evidence of changes from the original configuration.',
      commonMistake: 'Blaming users without correcting system failures.',
      action: 'Correct the underlying cause and verify effectiveness.',
      records: 'Incident/observation investigation and corrective action.',
      fieldProcedure: 'Common root causes include poor planning/design, incorrect erection, unauthorized alteration, overloading, weak foundation, component damage and environmental effects.',
      roles: 'Managers address system causes; supervisors prevent unsafe changes; HSE verifies corrective action.',
      preWork: 'Review drawings, RAMS, competency and previous defects when investigating recurring problems.',
      duringWork: 'Control change management and prohibit unauthorized modification.',
      monitoring: 'Look for evidence that the current arrangement differs from the approved configuration.',
      emergency: 'After an incident or significant damage, isolate first and investigate before re-use.',
      stopWork: 'Stop repeated unsafe work until the underlying cause is corrected.',
      checklist: 'Root cause; immediate cause; contributing factors; corrective owner; verification.',
      interview: 'Why is “worker not careful” usually insufficient as a root-cause statement?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '12',
    title: 'Risk & Consequences',
    introduction: 'Assess consequences for workers, public, property, plant and adjacent activities.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 12',
      title: 'Risk & Consequences',
      meaning: 'Assess consequences for workers, public, property, plant and adjacent activities.',
      hazards: 'Collapse can affect multiple levels and nearby work areas.',
      controls: 'Use risk assessment and critical-control verification for high-risk configurations.',
      fieldCheck: 'Check whether exclusion zones and emergency arrangements match the credible consequence.',
      commonMistake: 'Assessing only the person standing on the platform.',
      action: 'Expand the risk assessment to all exposed persons.',
      records: 'Risk assessment, emergency plan.',
      fieldProcedure: 'Risk assessment should consider workers, scaffolders, users, people below, public, plant, property and adjacent operations.',
      roles: 'Risk owners ensure controls are proportionate to the credible consequence.',
      preWork: 'Assess collapse/fall/falling-object scenarios and interface exposure before work.',
      duringWork: 'Prioritize critical controls for stability, edge protection, access and load management.',
      monitoring: 'Verify that exclusion zones and controls match the credible consequence.',
      emergency: 'Emergency planning should reflect the worst credible consequence identified.',
      stopWork: 'Stop when risk is not reduced to an acceptable controlled condition.',
      checklist: 'Hazard; exposed population; consequence; controls; residual risk; verification.',
      interview: 'Why must people below a scaffold be included in the risk assessment?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '13',
    title: 'Hierarchy of Controls',
    introduction: 'Control scaffold risks through design and engineering before relying on administrative controls or PPE.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 13',
      title: 'Hierarchy of Controls',
      meaning: 'Control scaffold risks through design and engineering before relying on administrative controls or PPE.',
      hazards: 'Administrative controls alone may not prevent collapse or falls.',
      controls: 'Eliminate unnecessary access; engineer stability and edge protection; use procedures, supervision and PPE as supporting controls.',
      fieldCheck: 'Verify engineering controls first during inspections.',
      commonMistake: 'Relying on helmets to compensate for missing guardrails.',
      action: 'Install/restore the physical control before work.',
      records: 'RAMS, design, inspection records.',
      fieldProcedure: 'Apply elimination and engineering controls first: avoid unnecessary work at height, design stable systems, provide edge protection and engineered access; procedures, supervision and PPE support these controls.',
      roles: 'Designers and managers control upstream risks; supervisors enforce procedures; users follow controls.',
      preWork: 'Ask whether the task can be redesigned or access method improved before relying on PPE.',
      duringWork: 'Maintain physical controls and prevent their removal without authorization.',
      monitoring: 'Inspect engineering controls before checking administrative controls/PPE.',
      emergency: 'Emergency arrangements must not depend on improvised rescue.',
      stopWork: 'Stop when a critical engineering control is missing or bypassed.',
      checklist: 'Elimination; engineering; administrative; PPE; verification.',
      interview: 'Why is PPE not a substitute for guardrails or scaffold stability?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '14',
    title: 'Scaffold Stability',
    introduction: 'Maintain the designed base, bracing, ties, standards, ledgers and structural configuration.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 14',
      title: 'Scaffold Stability',
      meaning: 'Maintain the designed base, bracing, ties, standards, ledgers and structural configuration.',
      hazards: 'Instability can result from missing ties, altered braces, settlement or excessive eccentric loading.',
      controls: 'Follow approved design/manufacturer requirements and protect critical structural members from unauthorized changes.',
      fieldCheck: 'Check plumb/level, bracing, ties and signs of movement.',
      commonMistake: 'Removing a tie to allow another trade to pass.',
      action: 'Stop use and restore the stability system.',
      records: 'Design, inspection, alteration records.',
      fieldProcedure: 'Stability depends on the complete structural system: foundation, standards, ledgers, transoms, bracing, ties, connections and approved geometry.',
      roles: 'Designer specifies stability; scaffolders install; inspectors verify; users protect the system from alteration.',
      preWork: 'Confirm stability arrangements before loading or allowing use.',
      duringWork: 'Protect ties/braces from removal and control interfaces with other trades.',
      monitoring: 'Check plumb/level, movement, settlement, ties, bracing and connection condition.',
      emergency: 'After impact or suspected movement, isolate and reassess before rescue or recovery work.',
      stopWork: 'Stop for movement, leaning, missing ties/bracing, settlement or unexplained configuration change.',
      checklist: 'Base; geometry; bracing; ties; connections; movement; external loads.',
      interview: 'What are common causes of scaffold instability?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '15',
    title: 'Bracing / Ties / Anchoring',
    introduction: 'Use bracing and ties required by the design/system and maintain them throughout use.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 15',
      title: 'Bracing / Ties / Anchoring',
      meaning: 'Use bracing and ties required by the design/system and maintain them throughout use.',
      hazards: 'Insufficient or removed ties/bracing can cause progressive instability.',
      controls: 'Install, inspect and protect ties/bracing; engineered alternatives require competent approval.',
      fieldCheck: 'Check tie pattern, condition and connections against the drawing.',
      commonMistake: 'Assuming one tie is enough for every configuration.',
      action: 'Isolate and obtain competent assessment.',
      records: 'Scaffold drawing, tie/bracing inspection.',
      fieldProcedure: 'Ties, braces and anchoring resist movement and transfer forces to the supporting structure.',
      roles: 'Only competent persons alter stability components; other trades must not remove them.',
      preWork: 'Verify tie/bracing arrangement against the approved design/system before use.',
      duringWork: 'Provide controlled temporary arrangements when a tie must be altered; restore and re-inspect before use.',
      monitoring: 'Check condition, pattern and connections of ties/braces.',
      emergency: 'Isolate the affected area if stability components are damaged or removed.',
      stopWork: 'Stop for missing/loose critical ties or braces or unauthorized alteration.',
      checklist: 'Tie/bracing pattern; connections; damage; alteration approval; reinspection.',
      interview: 'Why should a scaffold tie never be removed simply to create access?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '16',
    title: 'Platforms / Working Levels',
    introduction: 'Provide complete, suitable working platforms for the intended task and loading.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 16',
      title: 'Platforms / Working Levels',
      meaning: 'Provide complete, suitable working platforms for the intended task and loading.',
      hazards: 'Trips, falls through gaps and platform failure can occur.',
      controls: 'Use suitable boards/components, secure them, control gaps and maintain a clear work surface.',
      fieldCheck: 'Inspect boards, gaps, support and cleanliness.',
      commonMistake: 'Using damaged boards or leaving uncontrolled gaps.',
      action: 'Remove defective boards and correct the platform.',
      records: 'Platform inspection, component records.',
      fieldProcedure: 'Working platforms must be complete, suitable for the task and capable of supporting the intended load.',
      roles: 'Supervisor controls housekeeping and loading; users keep platforms clear and report damage.',
      preWork: 'Confirm platform type, support, condition, access and intended loading.',
      duringWork: 'Prevent gaps, unsecured components, damaged boards and uncontrolled material accumulation.',
      monitoring: 'Inspect platform continuity, support, condition, cleanliness and loading.',
      emergency: 'Falling-object controls and rescue access must remain effective while work is underway.',
      stopWork: 'Stop use of a platform with a structural defect, uncontrolled gap or excessive load.',
      checklist: 'Platform complete; supported; secure; clear; edge protected; load controlled.',
      interview: 'What should an HSE officer check on a scaffold platform?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '17',
    title: 'Guardrails / Toe Boards',
    introduction: 'Provide effective edge protection and falling-object controls at exposed working levels.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 17',
      title: 'Guardrails / Toe Boards',
      meaning: 'Provide effective edge protection and falling-object controls at exposed working levels.',
      hazards: 'Workers can fall and tools/materials can strike people below.',
      controls: 'Maintain guardrails, intermediate protection where required, toe boards and exclusion zones.',
      fieldCheck: 'Check every exposed edge, end and access opening.',
      commonMistake: 'Removing a guardrail temporarily and not restoring it.',
      action: 'Stop work at the exposed edge and reinstate protection.',
      records: 'Inspection/tagging records.',
      fieldProcedure: 'Edge protection prevents falls and toe boards help control falling objects at exposed edges.',
      roles: 'Supervisor ensures controls remain in place; users do not remove them without authorization.',
      preWork: 'Identify every exposed edge, end, opening and access transition.',
      duringWork: 'Restore protection immediately after temporary removal and control the area while it is absent.',
      monitoring: 'Check top/intermediate edge protection as applicable, toe boards and openings.',
      emergency: 'Rescue planning must account for workers exposed at open edges.',
      stopWork: 'Stop work at an unprotected edge where the risk is not otherwise controlled.',
      checklist: 'All exposed edges; openings; toe boards; temporary removals; reinstatement.',
      interview: 'Why should a removed guardrail trigger immediate control of the affected area?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '18',
    title: 'Access & Egress',
    introduction: 'Provide safe access designed for the scaffold configuration.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 18',
      title: 'Access & Egress',
      meaning: 'Provide safe access designed for the scaffold configuration.',
      hazards: 'Climbing standards, ledgers or braces can cause falls.',
      controls: 'Use approved ladders, stair towers or designed access; keep routes clear.',
      fieldCheck: 'Verify access from ground to each required working level.',
      commonMistake: 'Workers climbing outside the scaffold.',
      action: 'Block unsafe access and provide compliant access.',
      records: 'Access inspection, RAMS.',
      fieldProcedure: 'Access and egress should be purpose-designed for the scaffold and kept clear throughout use.',
      roles: 'Scaffolders install access; supervisors maintain routes; users use only approved access.',
      preWork: 'Plan access to all required work levels and emergency routes.',
      duringWork: 'Do not climb standards, ledgers or braces as normal access.',
      monitoring: 'Check route continuity, landings, gates/openings and obstructions.',
      emergency: 'Emergency access must remain usable during the task.',
      stopWork: 'Stop if workers must climb the scaffold structure or access is blocked.',
      checklist: 'Access route; condition; landings; obstructions; emergency route.',
      interview: 'What is the safest response when the planned access route is blocked?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '19',
    title: 'Ladders / Stair Towers',
    introduction: 'Control ladder angle, securing, landing arrangements and stair-tower integrity according to the applicable system requirements.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 19',
      title: 'Ladders / Stair Towers',
      meaning: 'Control ladder angle, securing, landing arrangements and stair-tower integrity according to the applicable system requirements.',
      hazards: 'Unsecured or poorly positioned ladders can cause slips and falls.',
      controls: 'Use suitable access equipment, secure it and maintain safe landings and handholds.',
      fieldCheck: 'Inspect ladder/stair condition and connection at each access route.',
      commonMistake: 'Using scaffold braces as ladders.',
      action: 'Remove unsafe access and provide the designed route.',
      records: 'Access inspection and training records.',
      fieldProcedure: 'Ladders and stair towers must be suitable, secured and integrated with the scaffold system.',
      roles: 'Competent persons install; supervisors maintain; users report damage.',
      preWork: 'Check ladder/stair arrangement, landings, handholds and securement before use.',
      duringWork: 'Prevent improvised ladder placement and unsafe climbing.',
      monitoring: 'Inspect access components and transitions at each level.',
      emergency: 'Provide safe evacuation route and prevent blocked stairs/landings.',
      stopWork: 'Stop for unsecured/damaged access equipment or unsafe transition.',
      checklist: 'Ladder/stair condition; securement; landing; handhold; clear route.',
      interview: 'Why is using scaffold braces as a ladder unsafe?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '20',
    title: 'Loading / Load Limits',
    introduction: 'Ensure platform loading remains within the designed and identified capacity.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 20',
      title: 'Loading / Load Limits',
      meaning: 'Ensure platform loading remains within the designed and identified capacity.',
      hazards: 'Overloading can cause board failure, local instability or collapse.',
      controls: 'Display/communicate loading requirements and control materials, workers and equipment.',
      fieldCheck: 'Check stored materials and concentrated loads during inspection.',
      commonMistake: 'Stacking blocks/materials without checking design capacity.',
      action: 'Remove excess load under controlled conditions.',
      records: 'Design/load information, inspection record.',
      fieldProcedure: 'Platform loading must remain within the design/system capacity and be managed for concentrated and distributed loads.',
      roles: 'Supervisor controls material quantities; workers use only the identified load arrangement.',
      preWork: 'Confirm the applicable load information before bringing materials onto the scaffold.',
      duringWork: 'Spread loads as designed, keep access clear and prevent uncontrolled stacking.',
      monitoring: 'Check material quantity, concentration, storage position and signs of distress.',
      emergency: 'If overload is suspected, isolate and control removal under competent direction.',
      stopWork: 'Stop for suspected overload, structural distress or unknown load capacity.',
      checklist: 'Load information; materials; concentration; access; structural condition.',
      interview: 'How should suspected scaffold overload be handled?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '21',
    title: 'Falling Objects',
    introduction: 'Prevent tools, materials and components from falling from scaffold levels.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 21',
      title: 'Falling Objects',
      meaning: 'Prevent tools, materials and components from falling from scaffold levels.',
      hazards: 'People below can suffer impact injuries.',
      controls: 'Use toe boards, containment, secured materials, exclusion zones and controlled lifting/handling.',
      fieldCheck: 'Check edges, openings and material storage.',
      commonMistake: 'Throwing materials between levels.',
      action: 'Stop unsafe handling and establish controlled movement.',
      records: 'Toolbox talk, inspection and lifting records.',
      fieldProcedure: 'Falling-object controls must protect people below, adjacent workers and the public.',
      roles: 'Supervision controls material handling; workers secure tools/materials; HSE verifies exclusion controls.',
      preWork: 'Identify work above/below and establish exclusion/containment requirements.',
      duringWork: 'Use toe boards, containment, secured tools/materials and controlled lifting/handling as applicable.',
      monitoring: 'Inspect edges, openings, storage and areas below.',
      emergency: 'Emergency response should include impact injury and dropped-object scenarios.',
      stopWork: 'Stop uncontrolled throwing, dropping or unsecured storage.',
      checklist: 'Edges; tools; materials; containment; exclusion zone; lifting route.',
      interview: 'What controls protect people working below a scaffold?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '22',
    title: 'Weather / Wind / Heat',
    introduction: 'Assess wind, rain, heat and other environmental conditions affecting scaffold stability and worker safety.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 22',
      title: 'Weather / Wind / Heat',
      meaning: 'Assess wind, rain, heat and other environmental conditions affecting scaffold stability and worker safety.',
      hazards: 'Wind can increase structural loading; heat can impair workers and equipment.',
      controls: 'Follow design/manufacturer weather limits and site heat controls; reassess after adverse conditions.',
      fieldCheck: 'Check weather exposure, sheeting/netting and stability before use.',
      commonMistake: 'Adding sheeting without assessing wind loading.',
      action: 'Stop use and obtain competent assessment when conditions exceed controls.',
      records: 'Weather monitoring, inspection records.',
      fieldProcedure: 'Environmental conditions can affect scaffold stability and worker safety. Wind, rain, heat and site changes require reassessment.',
      roles: 'Management defines monitoring; supervisors stop work when conditions exceed the controls/design basis.',
      preWork: 'Review forecast/current conditions and the effect of sheeting, netting or temporary coverings.',
      duringWork: 'Do not add coverings or change exposure without assessing the effect on stability.',
      monitoring: 'Inspect after adverse weather and after significant environmental changes.',
      emergency: 'Heat-stress controls and emergency response should be integrated for workers.',
      stopWork: 'Stop for unsafe wind/weather exposure, movement, damaged components or heat-related impairment.',
      checklist: 'Weather condition; coverings; movement; inspection; worker condition.',
      interview: 'Why can adding sheeting change scaffold risk?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '23',
    title: 'Electrical / Overhead Services',
    introduction: 'Control contact with overhead electrical lines and electrical hazards near scaffolding.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 23',
      title: 'Electrical / Overhead Services',
      meaning: 'Control contact with overhead electrical lines and electrical hazards near scaffolding.',
      hazards: 'Conductive scaffold can create fatal shock or arc-flash exposure.',
      controls: 'Identify services, maintain required clearances, isolate where possible and use authority controls/NOCs as applicable.',
      fieldCheck: 'Survey overhead services before erection and during changes.',
      commonMistake: 'Erecting scaffold without checking overhead lines.',
      action: 'Stop work and establish the required electrical/service controls.',
      records: 'Survey, NOC/permit, electrical risk assessment.',
      fieldProcedure: 'Scaffolding is conductive and can create severe electrical exposure near overhead or nearby electrical services.',
      roles: 'Project management coordinates authority/service controls; competent electrical persons address isolation where applicable.',
      preWork: 'Survey services and establish the applicable safe approach/clearance requirements from the current authority controls.',
      duringWork: 'Use isolation/de-energization where feasible and approved, barriers and controlled erection methods where required.',
      monitoring: 'Check service location, clearances and changes during erection/use.',
      emergency: 'Electrical emergency arrangements must include isolation and controlled rescue.',
      stopWork: 'Stop for unknown service location or inadequate electrical control.',
      checklist: 'Service survey; authority controls/NOCs; isolation; barriers; clearances; supervision.',
      interview: 'What must be done before erecting scaffold near an electrical service?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '24',
    title: 'Mobile / Tower / Special Scaffolds',
    introduction: 'Apply additional controls to mobile towers, suspended and special scaffold systems.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 24',
      title: 'Mobile / Tower / Special Scaffolds',
      meaning: 'Apply additional controls to mobile towers, suspended and special scaffold systems.',
      hazards: 'Movement, overturning, suspension failure or non-standard loads can cause falls/collapse.',
      controls: 'Use competent assembly, suitable foundations, wheel controls, design and manufacturer requirements.',
      fieldCheck: 'Check configuration, brakes/stabilisers, platform and intended use.',
      commonMistake: 'Moving a tower while people or unsecured materials remain on it.',
      action: 'Stop use and correct the configuration.',
      records: 'Manufacturer instructions, inspection, training.',
      fieldProcedure: 'Mobile/tower, suspended, cantilever, birdcage and special scaffolds require controls specific to their design and operating mode.',
      roles: 'Competent persons follow manufacturer/design instructions; users do not move or modify systems unless authorized.',
      preWork: 'Confirm system-specific stability, movement, access, loading and operating limitations.',
      duringWork: 'For mobile systems, control movement/use conditions; for suspended/special systems, follow the approved design and rescue arrangements.',
      monitoring: 'Inspect wheels/castors, locks, platforms, braces, ties and system-specific components as applicable.',
      emergency: 'Rescue planning must reflect the movement and elevation characteristics of the system.',
      stopWork: 'Stop for unauthorized movement, missing locks/braces, incompatible parts or deviation from design.',
      checklist: 'System type; stability; movement control; access; load; inspection; rescue.',
      interview: 'What additional controls should be considered for a mobile tower?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '25',
    title: 'RAMS / JSA / Risk Assessment',
    introduction: 'Make the scaffold method specific to erection, use, alteration and dismantling.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 25',
      title: 'RAMS / JSA / Risk Assessment',
      meaning: 'Make the scaffold method specific to erection, use, alteration and dismantling.',
      hazards: 'Generic RAMS can omit site-specific stability and interface risks.',
      controls: 'Include sequence, competent roles, exclusion zones, design, loading, access, rescue and change control.',
      fieldCheck: 'Compare field work with the approved RAMS.',
      commonMistake: 'Using a generic RAMS for a non-standard scaffold.',
      action: 'Revise and reapprove before continuing.',
      records: 'RAMS/JSA, approval records.',
      fieldProcedure: 'RAMS/JSA/risk assessment should translate the design and CoP requirements into the actual site method.',
      roles: 'Employer/project management approves the safe system; supervisor briefs workers; HSE verifies implementation.',
      preWork: 'Include erection, alteration, use, inspection and dismantling interfaces.',
      duringWork: 'Make critical controls observable and assign responsible persons.',
      monitoring: 'Field-check that actual work matches the RAMS and current revision.',
      emergency: 'Emergency/rescue arrangements must be part of the safe system, not an afterthought.',
      stopWork: 'Stop when workers are following an obsolete or materially different method.',
      checklist: 'Current RAMS; risk assessment; method; revision; briefing; field verification.',
      interview: 'What should trigger a RAMS review?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '26',
    title: 'PTW / Authorization',
    introduction: 'Use permits and authorisations where required by the site or interfacing activity.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 26',
      title: 'PTW / Authorization',
      meaning: 'Use permits and authorisations where required by the site or interfacing activity.',
      hazards: 'Scaffold work may interface with roads, electrical services, hot work or other controlled activities.',
      controls: 'Confirm required permits/NOCs and coordination before work.',
      fieldCheck: 'Check permit status and boundaries at pre-start.',
      commonMistake: 'Assuming scaffold erection never requires a permit.',
      action: 'Stop until required authorization is in place.',
      records: 'Permit/NOC and coordination records.',
      fieldProcedure: 'Where a permit, authorization, NOC or interface control is required by the project/authority, it must be completed before the affected work starts.',
      roles: 'Permit issuer, performing authority and supervisor must understand their respective responsibilities.',
      preWork: 'Confirm applicable permits/NOCs for location, services, traffic, work at height or other interfaces.',
      duringWork: 'Permit controls must be physically implemented and remain valid for the actual work.',
      monitoring: 'Check permit scope, validity, conditions and close-out.',
      emergency: 'Emergency work must follow site emergency authorization arrangements without bypassing critical safety controls.',
      stopWork: 'Stop if required authorization is missing, expired or conditions have changed materially.',
      checklist: 'Permit/NOC; scope; validity; conditions; isolations; close-out.',
      interview: 'Why is a permit not enough unless its conditions are implemented in the field?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '27',
    title: 'Safe Work Procedure',
    introduction: 'Control erection, use, alteration and dismantling as separate stages.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 27',
      title: 'Safe Work Procedure',
      meaning: 'Control erection, use, alteration and dismantling as separate stages.',
      hazards: 'Uncontrolled sequence changes can remove critical stability or fall protection.',
      controls: 'Use competent workers, progressive stability, exclusion zones and controlled handover.',
      fieldCheck: 'Observe the actual sequence, not just the paperwork.',
      commonMistake: 'Allowing trades to modify the scaffold themselves.',
      action: 'Stop and restore the approved configuration.',
      records: 'RAMS, handover and inspection records.',
      fieldProcedure: 'The safe work procedure should control erection, use, alteration and dismantling as distinct activities.',
      roles: 'Competent scaffolders execute; supervisor coordinates; HSE verifies; users comply with restrictions.',
      preWork: 'Brief sequence, access, exclusion zones, load controls, alteration restrictions and emergency arrangements.',
      duringWork: 'Maintain the designed configuration and inspect after changes.',
      monitoring: 'Monitor work continuously for deviation from the approved method.',
      emergency: 'Rescue must be practicable from the actual working level and access arrangement.',
      stopWork: 'Stop for deviation that affects stability, fall protection or safe access.',
      checklist: 'Method sequence; roles; exclusion; controls; inspection; handover.',
      interview: 'Why should alteration and dismantling have their own controlled method?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '28',
    title: 'Inspection & Tagging',
    introduction: 'Inspect before use and at the intervals/events required by the applicable CoP/site system, with clear status identification.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 28',
      title: 'Inspection & Tagging',
      meaning: 'Inspect before use and at the intervals/events required by the applicable CoP/site system, with clear status identification.',
      hazards: 'Workers may enter an unsafe or incomplete scaffold if status is unclear.',
      controls: 'Use competent inspection, defect control and a visible status/tagging system.',
      fieldCheck: 'Check inspection date, status, defects and whether alterations occurred.',
      commonMistake: 'Leaving an old green tag after a major alteration or adverse event.',
      action: 'Remove/replace status and isolate until re-inspected.',
      records: 'Inspection register, tag record, defect closure.',
      fieldProcedure: 'Inspection and status identification communicate whether a scaffold is fit for use. Inspection must be by a competent person at the intervals/events required by the current CoP and site system.',
      roles: 'Inspector records findings; supervisor controls access; management ensures defects are closed.',
      preWork: 'Inspect before first use/handover and after alterations, events or conditions requiring reinspection under the applicable requirements.',
      duringWork: 'Keep unsafe/incomplete scaffolds isolated and clearly identified.',
      monitoring: 'Verify status, inspection date, defects, alterations and surrounding conditions.',
      emergency: 'Emergency access must not rely on an unsafe scaffold.',
      stopWork: 'Stop use when inspection is overdue, status is unclear or a critical defect is open.',
      checklist: 'Inspection register; tag/status; defect list; closure evidence; reinspection.',
      interview: 'When should a scaffold be re-inspected?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '29',
    title: 'Competency & Responsibilities',
    introduction: 'Define responsibilities for designer, scaffolder, inspector, supervisor, HSE and users.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 29',
      title: 'Competency & Responsibilities',
      meaning: 'Define responsibilities for designer, scaffolder, inspector, supervisor, HSE and users.',
      hazards: 'Unclear responsibility leads to unauthorized changes and missed defects.',
      controls: 'Use trained/competent persons and clear authorization boundaries.',
      fieldCheck: 'Verify competency before assigning erection, inspection or alteration duties.',
      commonMistake: 'Allowing untrained workers to erect or modify scaffolds.',
      action: 'Remove from the task and assign competent personnel.',
      records: 'Training/certification and authorization records.',
      fieldProcedure: 'Competency must match the task: design, erection, alteration, inspection, supervision and use have different responsibilities.',
      roles: 'Define authorization boundaries and verify training/competence before assignment.',
      preWork: 'Confirm named competent persons and supervision before work begins.',
      duringWork: 'Prevent untrained persons from erecting, altering or inspecting scaffolds.',
      monitoring: 'Check competency records and actual task behavior.',
      emergency: 'Emergency roles and communication responsibilities should be clear.',
      stopWork: 'Stop when a critical task is assigned to an unqualified/unauthorized person.',
      checklist: 'Training; competence; authorization; supervision; role allocation.',
      interview: 'Who should be authorized to alter a scaffold?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '30',
    title: 'PPE',
    introduction: 'Use PPE as the final layer after engineered controls are established.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 30',
      title: 'PPE',
      meaning: 'Use PPE as the final layer after engineered controls are established.',
      hazards: 'Improper PPE can leave workers exposed to falls, impact, dust or other task hazards.',
      controls: 'Use task-appropriate helmet, footwear, gloves, eye protection, high visibility and fall protection where required by the risk assessment/system.',
      fieldCheck: 'Check PPE condition and correct use.',
      commonMistake: 'Using fall-arrest equipment without a suitable rescue plan.',
      action: 'Correct the PPE and rescue arrangement before work.',
      records: 'PPE inspection, training records.',
      fieldProcedure: 'PPE supports, but does not replace, engineering controls. Typical task-based PPE may include head, eye, hand, foot and high-visibility protection; fall protection is used where required by the approved risk control.',
      roles: 'Supervisor enforces correct PPE; workers inspect/use it; HSE verifies suitability.',
      preWork: 'Select PPE from the task risk assessment and compatibility with the scaffold work.',
      duringWork: 'Ensure fall-protection equipment has suitable anchorage, inspection and rescue arrangements where required.',
      monitoring: 'Check condition, fit and correct use.',
      emergency: 'A rescue plan is essential where fall-arrest equipment is used.',
      stopWork: 'Stop when required PPE/fall protection is unavailable, defective or incompatible.',
      checklist: 'PPE selection; condition; fit; inspection; compatibility; rescue.',
      interview: 'Why must fall-arrest use be linked to a rescue plan?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '31',
    title: 'Emergency / Rescue',
    introduction: 'Plan for falls, collapse, suspended-worker incidents, falling objects, electrical contact and medical emergencies.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 31',
      title: 'Emergency / Rescue',
      meaning: 'Plan for falls, collapse, suspended-worker incidents, falling objects, electrical contact and medical emergencies.',
      hazards: 'Improvised rescue can expose rescuers to the same hazard.',
      controls: 'Provide communication, rescue equipment, competent responders and exclusion controls appropriate to the scaffold.',
      fieldCheck: 'Confirm rescue route and emergency access remain usable.',
      commonMistake: 'Starting high-level work without a rescue plan.',
      action: 'Stop work until emergency arrangements are credible and communicated.',
      records: 'Emergency plan, drill/toolbox records.',
      fieldProcedure: 'Plan credible emergencies: fall, collapse, dropped object, electrical contact, medical event, fire and access obstruction as applicable.',
      roles: 'Emergency coordinator/site management leads response; trained responders perform rescue; others maintain exclusion and communication.',
      preWork: 'Confirm alarm, communication, access, rescue equipment and competent responders.',
      duringWork: 'Do not create a second casualty by entering an unstable or electrically energized area.',
      monitoring: 'Verify rescue route, access and equipment before work.',
      emergency: 'After an emergency, isolate the scaffold and prevent re-use until competent assessment is completed.',
      stopWork: 'Stop and reassess when emergency arrangements are absent or unusable.',
      checklist: 'Emergency contact; access; rescue equipment; responders; isolation; post-event inspection.',
      interview: 'What is the first safety priority during a scaffold collapse?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '32',
    title: 'Stop-Work Conditions',
    introduction: 'Define critical failures that require immediate isolation or reassessment.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 32',
      title: 'Stop-Work Conditions',
      meaning: 'Define critical failures that require immediate isolation or reassessment.',
      hazards: 'Continued use after a critical defect can turn a correctable defect into a major incident.',
      controls: 'Stop for instability, damaged/missing critical components, failed edge protection, unsafe access, uncontrolled alteration, overload, unsafe weather or electrical exposure.',
      fieldCheck: 'Check whether any critical control has failed.',
      commonMistake: 'Continuing because workers have already started.',
      action: 'Isolate, tag, rectify and re-inspect.',
      records: 'Stop-work/defect record.',
      fieldProcedure: 'Critical stop-work triggers include instability, damaged/missing critical components, failed edge protection, unsafe access, overload, unauthorized alteration, electrical exposure and unsafe environmental conditions.',
      roles: 'Every worker has a responsibility to stop and report unsafe conditions under the site system.',
      preWork: 'Brief stop-work triggers before starting.',
      duringWork: 'Isolate the affected area, rectify the cause and re-inspect before restart.',
      monitoring: 'Verify that the failed control is restored, not merely acknowledged.',
      emergency: 'Maintain exclusion until the hazard is controlled.',
      stopWork: 'Stop immediately for a credible immediate-danger condition.',
      checklist: 'Trigger; isolation; corrective action; competent verification; restart authorization.',
      interview: 'Give five conditions that require immediate scaffold isolation.',
    ),
  ),
  ScaffoldingGoldSection(
    number: '33',
    title: 'Unsafe Practices → Corrective Actions',
    introduction: 'Convert unsafe observations into specific, verified corrective actions.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 33',
      title: 'Unsafe Practices → Corrective Actions',
      meaning: 'Convert unsafe observations into specific, verified corrective actions.',
      hazards: 'Repeated unsafe practices indicate weak supervision or system control.',
      controls: 'Record condition, risk, immediate action, root cause, owner and verification.',
      fieldCheck: 'Photograph/describe the actual defect where appropriate.',
      commonMistake: 'Closing an observation with \'worker instructed\' only.',
      action: 'Address the physical/system cause and verify closure.',
      records: 'Observation, corrective-action and close-out records.',
      fieldProcedure: 'Corrective action should address the condition, cause and system weakness, with a named owner and verification.',
      roles: 'Supervisor owns immediate correction; responsible manager addresses systemic cause; HSE verifies closure.',
      preWork: 'Record the observation clearly enough that another person can understand the hazard.',
      duringWork: 'Prefer physical/system corrections over “worker instructed” as the only action.',
      monitoring: 'Reinspect after correction and confirm the risk is actually removed/reduced.',
      emergency: 'Escalate repeated defects and significant events for investigation.',
      stopWork: 'Do not close an observation without objective evidence of correction.',
      checklist: 'Observation; risk; immediate action; root cause; owner; due date; verification; closure.',
      interview: 'What makes a corrective action effective?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '34',
    title: 'Toolbox Talk',
    introduction: 'Use toolbox talks to communicate scaffold-specific critical controls before work.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 34',
      title: 'Toolbox Talk',
      meaning: 'Use toolbox talks to communicate scaffold-specific critical controls before work.',
      hazards: 'Workers may not understand loading, access, tagging or modification restrictions.',
      controls: 'Cover scaffold status, access, load limits, prohibited alterations, falling-object controls, weather and stop-work triggers.',
      fieldCheck: 'Ask workers to explain the critical controls back.',
      commonMistake: 'Signing attendance without checking understanding.',
      action: 'Repeat briefing and correct knowledge gaps.',
      records: 'Toolbox attendance and briefing content.',
      fieldProcedure: 'Toolbox talks should focus on the actual scaffold configuration, critical controls and changes for the day.',
      roles: 'Supervisor/competent person briefs; workers participate and demonstrate understanding.',
      preWork: 'Cover status/tagging, access, load limits, prohibited alterations, falling-object controls, weather and stop-work triggers.',
      duringWork: 'Use questions and worker feedback rather than attendance signatures alone.',
      monitoring: 'Observe whether workers apply the controls discussed.',
      emergency: 'Include emergency communication and rescue expectations.',
      stopWork: 'Stop or rebrief when workers cannot explain critical controls.',
      checklist: 'Topic; attendance; questions; understanding; actions; follow-up.',
      interview: 'How can an HSE officer check whether a toolbox talk was understood?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '35',
    title: 'Field Checklist',
    introduction: 'Use a top-to-bottom inspection route from foundation to highest working level.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 35',
      title: 'Field Checklist',
      meaning: 'Use a top-to-bottom inspection route from foundation to highest working level.',
      hazards: 'Skipping areas can leave critical defects undetected.',
      controls: 'Check foundation, standards, ledgers, braces, ties, platforms, guardrails, toe boards, access, loading, tags and surrounding interfaces.',
      fieldCheck: 'Perform a complete physical walk-through.',
      commonMistake: 'Checking only the green tag.',
      action: 'Isolate and record any critical defect.',
      records: 'Inspection checklist and defect log.',
      fieldProcedure: 'Use a structured top-to-bottom checklist rather than relying on memory or the status tag alone.',
      roles: 'Inspector performs; supervisor controls access; HSE samples/assures the process.',
      preWork: 'Start at foundation and continue through structure, ties/bracing, platforms, edge protection, access, loading and interfaces.',
      duringWork: 'Record defects precisely and isolate critical failures.',
      monitoring: 'Repeat checks after correction and required events.',
      emergency: 'Include emergency route and exclusion zone in the field check.',
      stopWork: 'Stop when the checklist identifies a critical uncontrolled defect.',
      checklist: 'Foundation; structure; stability; platforms; edge protection; access; load; environment; tag.',
      interview: 'What should a field checklist prevent?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '36',
    title: 'Quick Reference',
    introduction: 'Provide a compact field sequence for supervisors and HSE officers.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 36',
      title: 'Quick Reference',
      meaning: 'Provide a compact field sequence for supervisors and HSE officers.',
      hazards: 'Important controls can be missed under time pressure.',
      controls: 'Use: DESIGN → FOUNDATION → STRUCTURE → TIES/BRACING → PLATFORM → EDGE PROTECTION → ACCESS → LOAD → INTERFACES → INSPECTION → TAG → USE.',
      fieldCheck: 'Use the sequence during every field verification.',
      commonMistake: 'Treating the tag as a substitute for visual inspection.',
      action: 'Follow the sequence and escalate discrepancies.',
      records: 'Quick-reference checklist.',
      fieldProcedure: 'Quick sequence: NEED/DESIGN → FOUNDATION → STRUCTURE → TIES/BRACING → PLATFORM → EDGE PROTECTION → ACCESS → LOAD → INTERFACES → INSPECTION → STATUS → USE.',
      roles: 'Supervisor uses the sequence for daily field verification; HSE can use it for observation/audit sampling.',
      preWork: 'Use the sequence before work and after significant change.',
      duringWork: 'Do not treat the quick reference as a replacement for the full CoP/design.',
      monitoring: 'Verify each critical control physically.',
      emergency: 'Emergency/rescue remains part of the full system even when using the quick check.',
      stopWork: 'Stop if any critical control in the sequence fails.',
      checklist: 'Use the sequence consistently and record exceptions.',
      interview: 'What is the correct order of a basic scaffold field check?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '37',
    title: 'UAE / Abu Dhabi / Dubai Applicability',
    introduction: 'Keep Abu Dhabi requirements separate from Dubai and other jurisdictional requirements.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 37',
      title: 'UAE / Abu Dhabi / Dubai Applicability',
      meaning: 'Keep Abu Dhabi requirements separate from Dubai and other jurisdictional requirements.',
      hazards: 'Transferring a Dubai rule into Abu Dhabi without verification can create incorrect compliance advice.',
      controls: 'Use Abu Dhabi ADOSH-SF/ADPHC sources for Abu Dhabi; cross-reference other jurisdictions separately.',
      fieldCheck: 'Check jurisdiction and current document version before quoting a requirement.',
      commonMistake: 'Copying Dubai scaffolding content into Abu Dhabi unchanged.',
      action: 'Verify against the applicable authority.',
      records: 'Legal register, source/version record.',
      fieldProcedure: 'For Abu Dhabi, use the current ADOSH-SF/ADPHC requirements and project legal register. Dubai and other emirates must be treated as separate jurisdictional references.',
      roles: 'Legal/HSE management controls the jurisdictional register; site teams apply the requirements for the actual location and client.',
      preWork: 'Confirm emirate, authority, project/client requirements and current document revision before quoting a legal value.',
      duringWork: 'Do not copy jurisdiction-specific limits into another emirate without verification.',
      monitoring: 'Check source/version in audits and compliance reviews.',
      emergency: 'Emergency requirements may also depend on site/client authority arrangements.',
      stopWork: 'Stop compliance decisions based on an obsolete or wrong-jurisdiction source.',
      checklist: 'Jurisdiction; source; version; effective date; project/client requirements.',
      interview: 'Why should Abu Dhabi and Dubai requirements not be mixed without verification?',
    ),
  ),
  ScaffoldingGoldSection(
    number: '38',
    title: 'Official Regulatory References',
    introduction: 'Use the current official Abu Dhabi publication as the controlling regulatory source.',
    point: ScaffoldingGoldPoint(
      clause: 'Step 38',
      title: 'Official Regulatory References',
      meaning: 'Use the current official Abu Dhabi publication as the controlling regulatory source.',
      hazards: 'Outdated or secondary material can contain superseded requirements.',
      controls: 'Primary baseline: ADOSH-SF CoP 26.0 — Scaffolding, Version 4.1. Cross-reference other applicable CoPs and authority requirements where relevant.',
      fieldCheck: 'Record source title, version, effective date and applicability.',
      commonMistake: 'Using an old uncontrolled PDF as the legal basis.',
      action: 'Update the legal/reference register and reverify critical numeric requirements.',
      records: 'Official CoP, legal register, revision record.',
      fieldProcedure: 'Primary regulatory baseline for this module: ADOSH-SF CoP 26.0 — Scaffolding, Version 4.1, dated 16 February 2026. The official ADPHC publication remains the controlling source.',
      roles: 'Use the official source for legal interpretation and verify project/client requirements separately.',
      preWork: 'Record the document title, version/date and applicable sections in the legal/reference register.',
      duringWork: 'Cross-reference related requirements such as working at height, plant/traffic, electrical and emergency controls where applicable.',
      monitoring: 'Recheck the current official publication before issuing compliance-critical advice.',
      emergency: 'Emergency actions should follow the site emergency plan and authority requirements.',
      stopWork: 'Do not rely on uncontrolled or superseded copies for compliance decisions.',
      checklist: 'Official CoP; legal register; revision history; project requirements; related CoPs.',
      interview: 'What is the controlling source for Abu Dhabi scaffolding compliance?',
    ),
  ),
];
