import 'package:flutter/material.dart';
import 'models/reference_topic.dart';

/// SafeNexus HSE — Dubai HSE professional topic-by-topic reference.
/// This file preserves all existing Dubai topic IDs and adds the same professional, tappable structure to every topic.
class DubaiHseDetailPage extends StatelessWidget {
  final ReferenceTopic topic;
  const DubaiHseDetailPage({super.key, required this.topic});
  static const Color primary = Color(0xFF0B6B4F);
  static const Color background = Color(0xFFF5F8F7);

  @override
  Widget build(BuildContext context) {
    final data = _topicData[topic.id];
    if (data == null) return _fallback(context);
    final sections = data.sections;
    return Scaffold(
      backgroundColor: background,
      appBar: AppBar(
        title: Text(data.title, maxLines: 2, overflow: TextOverflow.ellipsis),
        backgroundColor: primary, foregroundColor: Colors.white,
      ),
      body: ListView(padding: const EdgeInsets.fromLTRB(16, 10, 16, 24), children: [
        _intro(data),
        _section(context, '🏗️ Types / Systems', data.types, Icons.category_outlined),
        _section(context, '🔧 Components / Key Items', data.items, Icons.build_outlined),
        _section(context, 'Purpose & Scope', sections['Purpose & Scope']!, Icons.menu_book_outlined),
        _section(context, 'Technical Requirements', sections['Technical Requirements']!, Icons.menu_book_outlined),
        _section(context, 'Main Hazards', sections['Main Hazards']!, Icons.warning_amber_outlined),
        _section(context, 'Safety Controls', sections['Safety Controls']!, Icons.shield_outlined),
        _section(context, 'Inspection & Verification', sections['Inspection & Verification']!, Icons.fact_check_outlined),
        _section(context, 'Stop-Work Conditions', sections['Stop-Work Conditions']!, Icons.block_outlined),
        _section(context, 'Responsibilities', sections['Responsibilities']!, Icons.groups_outlined),
        _section(context, 'Worker Responsibilities', sections['Worker Responsibilities']!, Icons.groups_outlined),
        _section(context, 'Emergency Response', sections['Emergency Response']!, Icons.emergency_outlined),
        _section(context, 'Practical Site Example', sections['Practical Site Example']!, Icons.engineering_outlined),
        _section(context, 'Quick Learning Formula', sections['Quick Learning Formula']!, Icons.psychology_outlined),
      ]),
    );
  }

  Widget _intro(_TopicData data) => Card(
    elevation: 1,
    child: Padding(padding: const EdgeInsets.all(18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      const Text('📖 Introduction — What is it?', style: TextStyle(fontSize: 21, fontWeight: FontWeight.w800)),
      const SizedBox(height: 10),
      Text(data.intro, style: const TextStyle(fontSize: 16, height: 1.6)),
    ])),
  );

  Widget _section(BuildContext context, String title, List<_DetailItem> values, IconData icon) => Card(
    margin: const EdgeInsets.only(top: 10),
    child: ExpansionTile(
      leading: Icon(icon, color: primary), title: Text(title, style: const TextStyle(fontWeight: FontWeight.w800)),
      children: [for (int i = 0; i < values.length; i++) ListTile(
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 2),
        leading: CircleAvatar(radius: 15, backgroundColor: primary, child: Text('${i + 1}', style: const TextStyle(color: Colors.white, fontSize: 12))),
        title: Text(values[i].title, style: const TextStyle(fontWeight: FontWeight.w700)),
        subtitle: Text(values[i].detail, maxLines: 2, overflow: TextOverflow.ellipsis),
        trailing: const Icon(Icons.chevron_right),
        onTap: () => Navigator.of(context).push(MaterialPageRoute(builder: (_) => DubaiHseItemDetailPage(sectionTitle: title, item: values[i].title, detail: values[i].detail))),
      )],
    ),
  );

  Widget _fallback(BuildContext context) => Scaffold(
    appBar: AppBar(title: Text(topic.title), backgroundColor: primary, foregroundColor: Colors.white),
    body: Padding(padding: const EdgeInsets.all(16), child: Text(topic.description.isNotEmpty ? topic.description : 'Dubai HSE learning reference.', style: const TextStyle(fontSize: 16, height: 1.5))),
  );
}

class DubaiHseItemDetailPage extends StatelessWidget {
  final String sectionTitle; final String item; final String detail;
  const DubaiHseItemDetailPage({super.key, required this.sectionTitle, required this.item, required this.detail});
  @override Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(title: Text(item, maxLines: 2, overflow: TextOverflow.ellipsis), backgroundColor: DubaiHseDetailPage.primary, foregroundColor: Colors.white),
    body: ListView(padding: const EdgeInsets.all(16), children: [
      Text(sectionTitle, style: const TextStyle(color: DubaiHseDetailPage.primary, fontWeight: FontWeight.w800)),
      const SizedBox(height: 8), Text(item, style: TextStyle(fontSize: 24, fontWeight: FontWeight.w800)),
      const SizedBox(height: 16), Card(child: Padding(padding: const EdgeInsets.all(18), child: Text(detail, style: TextStyle(fontSize: 16, height: 1.65)))),
    ]),
  );
}

class _DetailItem { final String title; final String detail; const _DetailItem({required this.title, required this.detail}); }
class _TopicData {
  final String title, intro; final List<_DetailItem> types, items; final Map<String, List<_DetailItem>> sections;
  const _TopicData({required this.title, required this.intro, required this.types, required this.items, required this.sections});
}

final Map<String, _TopicData> _topicData = {
  'dubai_construction_safety': _makeTopic(
    title: 'Dubai Construction Safety Framework',
    intro: 'A project-wide framework for planning, coordinating, supervising and verifying safe construction work in Dubai.',
    types: 'Planning & mobilisation|Construction execution|High-risk work control|SIMOPS / interface control',
    components: 'HSE plan|Risk assessment|Method statement|Permit to work|Competent person|Inspection record',
    requirements: 'Project scope, responsibilities, legal requirements, risk controls and emergency arrangements are defined before work starts.',
    hazards: 'Uncontrolled work|SIMOPS conflict|Plant and people interface|Public exposure|Critical barrier failure',
    controls: 'Approved planning, competent supervision, segregation, permits, inspections and corrective-action tracking.',
    inspection: 'Verify documents and field controls before start, during changes and after corrective actions.',
    stop: 'Stop when critical controls are absent, conditions differ materially from the approved method, or serious exposure is uncontrolled.',
    responsibilities: 'Management provides resources and authority; HSE verifies; supervisors control the workface.',
    worker: 'Follow approved methods, use required PPE, report defects and stop/report unsafe work.',
    emergency: 'Raise alarm, stop work, isolate hazards where safe, protect the area and follow the project emergency plan.',
    example: 'A crane lift conflicts with façade work below; the lift is paused, the lower area is isolated and the sequence is re-planned before restart.',
    learning: 'PLAN → ASSESS → CONTROL → VERIFY → EXECUTE → REVIEW',
  ),
  'dubai_hse_management': _makeTopic(
    title: 'HSE Management System',
    intro: 'The management system that turns Dubai construction safety requirements into responsibilities, procedures, risk controls, monitoring and continual improvement.',
    types: 'Leadership & governance|Project HSE planning|Operational control|Performance improvement',
    components: 'HSE policy|HSE plan|Roles matrix|Training matrix|Inspection programme|Corrective-action register',
    requirements: 'Define accountabilities, resources, competence, communication, document control, monitoring and review.',
    hazards: 'Weak leadership|Unclear accountability|Poor document control|Repeated findings|Inadequate competence',
    controls: 'Leadership walkdowns, clear responsibilities, risk-based inspections, training, audits and action verification.',
    inspection: 'Check whether documented arrangements are implemented at the workface, not only signed.',
    stop: 'Stop or suspend affected work where the management system has failed to control a significant risk.',
    responsibilities: 'Management leads and resources; HSE advises and verifies; supervisors implement.',
    worker: 'Understand the site rules, follow procedures and report gaps or changes.',
    emergency: 'Use the site emergency system, preserve evidence and review controls before restart.',
    example: 'A repeated scaffold defect is found; management assigns ownership, HSE verifies corrective action and supervision is strengthened.',
    learning: 'LEAD → PLAN → CONTROL → CHECK → IMPROVE',
  ),
  'dubai_risk_assessment': _makeTopic(
    title: 'Health & Safety Risk Assessment',
    intro: 'A structured process for identifying hazards, evaluating risk, selecting controls and confirming residual risk before and during work.',
    types: 'Task risk assessment|Activity / method risk assessment|Dynamic assessment|Change assessment',
    components: 'Hazard register|Risk matrix|Control hierarchy|Residual risk|Review trigger|Approval record',
    requirements: 'Identify people, hazards, existing controls, additional controls and residual risk; review when conditions change.',
    hazards: 'Missed hazard|Poor control selection|Over-reliance on PPE|Changed conditions|Uncommunicated assessment',
    controls: 'Use hierarchy of controls, involve competent people, brief workers and verify controls in the field.',
    inspection: 'Review before work, after incidents/near misses, after changes and at defined intervals.',
    stop: 'Stop when risk is not adequately controlled or the assessment no longer reflects actual conditions.',
    responsibilities: 'Risk owner approves; competent assessor develops; supervisor implements; workers participate.',
    worker: 'Read and understand the assessment, follow controls and report new hazards.',
    emergency: 'Protect people first, escalate the event and reassess before restart.',
    example: 'Excavation ground conditions change after rain; work stops and the assessment is revised before entry.',
    learning: 'IDENTIFY → ASSESS → CONTROL → VERIFY → REVIEW',
  ),
  'dubai_hse_plan': _makeTopic(
    title: 'Construction HSE Plan',
    intro: 'The project-specific plan that defines how HSE requirements will be organised, controlled and monitored throughout construction.',
    types: 'Project HSE plan|Activity plans|Emergency planning|Monitoring programme',
    components: 'Organisation chart|Legal register|Risk register|Emergency plan|Training matrix|Inspection schedule',
    requirements: 'Set project objectives, responsibilities, risk controls, emergency arrangements, welfare, environmental controls and monitoring.',
    hazards: 'Missing controls|Unclear roles|Poor contractor coordination|Inadequate emergency readiness',
    controls: 'Approval before mobilisation, worker induction, coordination meetings, inspections and management review.',
    inspection: 'Verify that the plan matches current work fronts, contractors and project phases.',
    stop: 'Stop affected work where required plan controls or approvals are absent.',
    responsibilities: 'Project management owns implementation; HSE coordinates and monitors.',
    worker: 'Comply with site arrangements and raise conflicts or missing controls.',
    emergency: 'Follow project emergency arrangements and account for personnel.',
    example: 'A new high-risk activity is introduced; the HSE plan and supporting controls are updated before mobilisation.',
    learning: 'PLAN → MOBILISE → CONTROL → MONITOR → REVIEW',
  ),
  'dubai_work_at_height': _makeTopic(
    title: 'Work at Height',
    intro: 'Work where a person could fall from a level and suffer injury, requiring suitable planning, access, fall prevention and rescue arrangements.',
    types: 'Fixed scaffold|Mobile access tower|MEWP|Ladder access|Roof / edge work',
    components: 'Working platform|Guardrail|Toe board|Harness & lanyard|Anchor / lifeline|Access system',
    requirements: 'Select collective fall prevention first where practicable; ensure suitable access, edge protection, equipment condition and rescue planning.',
    hazards: 'Falls from edge|Falls through openings|Dropped objects|Unsafe access|Equipment failure',
    controls: 'Guardrails, covers, exclusion zones, inspected access equipment, tool control and suitable rescue arrangements.',
    inspection: 'Inspect access, platforms, edge protection, anchor systems and equipment before use and after changes.',
    stop: 'Stop for missing edge protection, unsafe access, damaged equipment, unsuitable weather or ineffective rescue arrangements.',
    responsibilities: 'Supervisor controls the task; competent persons inspect safety-critical systems; workers use them correctly.',
    worker: 'Use designated access, maintain three points where applicable, secure tools and report defects.',
    emergency: 'Prevent secondary falls, raise alarm and use the planned rescue system; do not improvise.',
    example: 'A roof opening is found without a secure cover; work stops until the opening is protected and verified.',
    learning: 'PREVENT → PROTECT → ACCESS → INSPECT → RESCUE',
  ),
  'dubai_scaffolding': _makeTopic(
    title: 'Scaffolding Safety',
    intro: 'Temporary structures used to provide safe access, working platforms and fall protection. Selection, erection, inspection, modification and dismantling require competent control.',
    types: 'Fixed / Static Scaffold|Independent Scaffold|Tied Scaffold|Mobile Scaffold|Tower Scaffold|Access Scaffold|Birdcage Scaffold|Suspended Scaffold|Cantilever Scaffold|System Scaffold|Tube & Fitting Scaffold|Special-Purpose Scaffold',
    components: 'Standard|Ledger|Transom|Base Plate|Sole Board|Brace|Tie|Coupler|Platform|Guardrail / Handrail|Intermediate Rail|Toe Board|Access Ladder|Scaffold Stair|Castor / Wheel|Base Jack|Scaffold Tag',
    requirements: 'Use a suitable design/system, stable foundation, correct erection sequence, required bracing/ties, safe access, edge protection and inspection/status controls.',
    hazards: 'Fall from height|Scaffold collapse|Falling objects|Overloading|Unstable foundation|Missing ties/bracing|Unsafe access|Weather',
    controls: 'Competent erection, exclusion zones, approved modifications, inspection, tagging, housekeeping and load control.',
    inspection: 'Inspect foundation, standards, ledgers, transoms, bracing, ties, platforms, guardrails, toe boards, access, damage and modifications.',
    stop: 'Stop for instability, missing critical edge protection, deteriorated foundation, missing required ties/bracing, damaged platform, overload or unauthorised modification.',
    responsibilities: 'Competent person controls erection/inspection; supervisor controls use; workers do not alter safety-critical parts.',
    worker: 'Use only authorised scaffolds, respect tags and loads, never remove ties/bracing without approval.',
    emergency: 'Stop work, isolate the scaffold, prevent access and use the site rescue/emergency plan.',
    example: 'A scaffold tie is removed to move materials; work stops, the scaffold is assessed and the approved stability arrangement is restored before re-inspection.',
    learning: 'BASE → FRAME → BRACE → TIE → PLATFORM → GUARDRAIL → ACCESS → LOAD → INSPECT → TAG → USE',
  ),
  'dubai_lifting': _makeTopic(
    title: 'Lifting Operations',
    intro: 'Planned movement of loads using cranes, hoists or other lifting equipment with competent planning, certified equipment and controlled exclusion zones.',
    types: 'Mobile crane|Tower crane|Crawler crane|Truck-mounted crane|Hoist|Personnel lifting|Critical / heavy lift',
    components: 'Crane|Hook & latch|Wire rope|Chain / web sling|Shackle|Spreader beam|Tag line|Load indicator|Outrigger|Lift plan',
    requirements: 'Confirm lift plan, equipment suitability, inspection/certification, load data, ground conditions, communication and exclusion zones.',
    hazards: 'Dropped load|Overturning|Crane collision|Rigging failure|Power-line contact|People under load',
    controls: 'Competent lifting team, certified accessories, clear signals, exclusion zones, ground verification and weather monitoring.',
    inspection: 'Pre-use inspection, accessory checks, crane setup verification and periodic examination as applicable.',
    stop: 'Stop for overload, unstable setup, damaged lifting gear, loss of communication, people in exclusion zone or unsafe weather.',
    responsibilities: 'Appointed person / lift planner plans; operator operates; rigger/signaller controls the load; HSE verifies.',
    worker: 'Never stand under suspended loads; follow signals; inspect accessories and maintain exclusion.',
    emergency: 'Stop movement, lower/load-secure if safe, raise alarm and follow emergency response without entering danger zones.',
    example: 'A mobile crane is set up near an excavation; lifting is stopped until ground bearing and setup controls are verified.',
    learning: 'PLAN → SET UP → RIG → EXCLUDE → LIFT → CONTROL → LOWER → CLOSE',
  ),
  'dubai_excavation': _makeTopic(
    title: 'Excavation & Trenching',
    intro: 'Ground-breaking work including trenches, pits and foundations where collapse, falls, services and water can create serious hazards.',
    types: 'Open excavation|Trench|Foundation excavation|Deep excavation|Utility trench|Manhole / pit',
    components: 'Excavation edge|Access ladder / stair|Shoring|Trench box|Benching|Sloping|Spoil pile|Barricade|Dewatering|Service identification',
    requirements: 'Confirm underground services, ground conditions, protective system, access/egress, edge protection, spoil control and water management.',
    hazards: 'Cave-in|Falls into excavation|Buried services|Plant edge collapse|Water ingress|Falling materials|Atmospheric hazards',
    controls: 'Competent inspection, protective systems, safe access, edge barriers, spoil setbacks and plant exclusion.',
    inspection: 'Inspect after shift, rain, vibration, change in ground condition and before entry; verify protective systems.',
    stop: 'Stop for unsupported faces, damaged shoring, water ingress, unidentified services, unsafe access or plant too close to the edge.',
    responsibilities: 'Competent person controls excavation; survey/service teams verify interfaces; supervisors enforce controls.',
    worker: 'Stay outside exclusion zones, use designated access and report cracking, water or service discoveries.',
    emergency: 'Evacuate the excavation, isolate plant/services where safe and activate rescue arrangements; do not enter an unstable trench.',
    example: 'A trench develops cracking after rain; workers are withdrawn and the protective system/ground condition is reassessed before restart.',
    learning: 'IDENTIFY SERVICES → ASSESS GROUND → PROTECT → ACCESS → INSPECT → ENTER',
  ),
  'dubai_confined_space': _makeTopic(
    title: 'Confined Space Entry',
    intro: 'Entry into a space not designed for continuous occupancy where atmospheric, engulfment, access or rescue hazards may exist.',
    types: 'Tank / vessel|Manhole|Sewer / chamber|Pit|Duct / enclosed void',
    components: 'Entry permit|Gas detector|Ventilation|Isolation|Harness / lifeline|Standby person|Rescue equipment',
    requirements: 'Use permit-to-work, isolation, atmospheric testing, ventilation, competent supervision, standby and a tested rescue plan.',
    hazards: 'Oxygen deficiency|Toxic gas|Flammable atmosphere|Engulfment|Heat|Difficult rescue',
    controls: 'Isolation, continuous/periodic monitoring as required, forced ventilation, communication and dedicated rescue arrangements.',
    inspection: 'Test atmosphere before entry and as required; verify isolation, equipment and standby arrangements.',
    stop: 'Stop for failed gas test, loss of ventilation, isolation failure, alarm, communication loss or rescue readiness failure.',
    responsibilities: 'Entry supervisor controls permit; authorised entrants follow controls; standby person remains outside and attentive.',
    worker: 'Never enter without authorisation; monitor conditions; maintain communication and exit on alarm.',
    emergency: 'Raise alarm, do not make an unplanned rescue entry, use trained rescue team and isolate hazards.',
    example: 'A manhole test shows an unsafe atmosphere; entry is cancelled, ventilation/isolation is reviewed and the atmosphere is retested.',
    learning: 'ISOLATE → TEST → VENTILATE → AUTHORISE → ENTER → MONITOR → RESCUE',
  ),
  'dubai_electrical': _makeTopic(
    title: 'Electrical Safety',
    intro: 'Controls for electrical systems, temporary power, tools and work near electrical sources to prevent shock, arc, fire and unintended energisation.',
    types: 'LV systems|Temporary distribution|Portable tools|Isolation / LOTO|Electrical work near services',
    components: 'DB / panel|RCD / protection|Cable|Isolation point|LOTO device|Test instrument',
    requirements: 'Use competent electrical personnel, suitable protection, isolation/LOTO where required, inspected equipment and controlled temporary installations.',
    hazards: 'Electric shock|Arc flash|Fire|Damaged cable|Backfeed|Contact with live parts',
    controls: 'Isolation, testing, guarding, RCD/protection, cable management, dry conditions and controlled access.',
    inspection: 'Inspect panels, cables, plugs, tools, protection and isolation before use and after damage or changes.',
    stop: 'Stop for exposed live parts, damaged cables, failed protection, unknown isolation or water creating electrical danger.',
    responsibilities: 'Authorised electrical persons perform safety-critical work; supervisors control permits and isolations.',
    worker: 'Do not bypass protection or use damaged equipment; report defects immediately.',
    emergency: 'Do not touch a casualty until energy is isolated; raise alarm and use trained first aid/rescue procedures.',
    example: 'A damaged temporary cable is found across an access route; it is isolated and replaced before work resumes.',
    learning: 'ISOLATE → LOCK → TEST → PROTECT → USE → VERIFY',
  ),
  'dubai_hot_work': _makeTopic(
    title: 'Hot Work Safety',
    intro: 'Controlled activities that generate flame, heat, sparks or ignition sources and can start fires or explosions.',
    types: 'Welding|Cutting|Grinding|Brazing / soldering|Heating',
    components: 'Hot-work permit|Fire extinguisher|Fire watch|Gas cylinders|Screens|Spark containment',
    requirements: 'Confirm permit, combustible control, gas-cylinder arrangements, fire protection, ventilation and post-work fire watch.',
    hazards: 'Fire|Explosion|Gas release|Burns|Fumes|Sparks reaching adjacent areas',
    controls: 'Remove/cover combustibles, isolate sources, provide extinguishers, screens, ventilation and fire watch.',
    inspection: 'Check work area, equipment, hoses/cables, cylinders, permit conditions and surrounding interfaces before and during work.',
    stop: 'Stop for uncontrolled combustibles, missing permit, gas leak, inadequate fire protection, unsafe ventilation or changing conditions.',
    responsibilities: 'Permit issuer authorises; supervisor controls; fire watch monitors; workers maintain equipment and method.',
    worker: 'Follow permit, maintain housekeeping, use PPE and report sparks, fumes or gas issues.',
    emergency: 'Raise fire alarm, isolate energy/gas where safe and evacuate; use extinguisher only if trained and conditions permit.',
    example: 'Grinding sparks reach stored materials; work stops and the area is cleared and screened before restarting.',
    learning: 'PERMIT → CLEAR → PROTECT → WORK → FIRE WATCH → CHECK',
  ),
  'dubai_traffic': _makeTopic(
    title: 'Construction Traffic Management',
    intro: 'Controls for vehicles, mobile plant, pedestrians and deliveries within construction sites and public interfaces.',
    types: 'Site traffic plan|Pedestrian segregation|Delivery control|Plant movement|Public interface',
    components: 'Traffic route|Barrier|Gate|Banksman|Signage|Wheel stop',
    requirements: 'Separate people and vehicles, control gates/routes, manage reversing, speed, parking, deliveries and public exposure.',
    hazards: 'Vehicle-pedestrian collision|Reversing incident|Plant strike|Poor visibility|Public intrusion',
    controls: 'Segregation, one-way routes where suitable, trained banksmen, lighting, signs and controlled access.',
    inspection: 'Inspect routes, barriers, gates, lighting, signs and changing work interfaces.',
    stop: 'Stop when segregation fails, routes are blocked, visibility is inadequate or unsafe reversing/interaction is uncontrolled.',
    responsibilities: 'Traffic manager/supervisor controls routes; drivers/operators follow site rules; HSE verifies.',
    worker: 'Use designated routes, obey banksman signals and never enter exclusion zones.',
    emergency: 'Secure the area, stop vehicles, call emergency services and provide first aid without creating another collision.',
    example: 'A delivery truck arrives during a pedestrian movement; the delivery is held until the route is segregated.',
    learning: 'SEPARATE → CONTROL → SIGNAL → MOVE → VERIFY',
  ),
  'dubai_demolition': _makeTopic(
    title: 'Demolition Safety',
    intro: 'Planned dismantling or removal of structures with controls for structural stability, services, falling materials, dust and public protection.',
    types: 'Soft strip|Partial demolition|Top-down demolition|Mechanical demolition|Controlled dismantling',
    components: 'Demolition plan|Temporary support|Exclusion zone|Plant|Dust suppression|Service isolation',
    requirements: 'Survey the structure, identify services, establish sequence, temporary works, exclusion zones, plant limits and emergency arrangements.',
    hazards: 'Unexpected collapse|Falling debris|Asbestos / hazardous material|Utility strike|Dust|Plant interaction',
    controls: 'Engineered sequence, competent supervision, isolation, exclusion, dust control and continuous structural assessment.',
    inspection: 'Inspect structure, temporary supports, plant, exclusion zones and conditions before each phase.',
    stop: 'Stop for unexpected movement, loss of support, unidentified service/material, public exposure or uncontrolled debris.',
    responsibilities: 'Demolition engineer/competent person controls sequence; supervisor manages workface; HSE monitors.',
    worker: 'Stay outside exclusion zones, follow sequence and report cracking or unexpected movement.',
    emergency: 'Evacuate affected zone, raise alarm and do not approach unstable structure until competent assessment.',
    example: 'Unexpected movement occurs during wall removal; the area is evacuated and the sequence is reassessed before continuation.',
    learning: 'SURVEY → ISOLATE → SUPPORT → EXCLUDE → SEQUENCE → DEMOLISH → VERIFY',
  ),
  'dubai_temporary_works': _makeTopic(
    title: 'Temporary Works Safety',
    intro: 'Safety management for temporary structures and support systems that carry loads or maintain stability during construction.',
    types: 'Formwork|Falsework|Shoring|Temporary platforms|Propping|Temporary access',
    components: 'Design / calculation|Temporary works register|Support|Prop|Brace|Inspection record',
    requirements: 'Use competent design/approval, correct materials, erection sequence, load control, inspection and controlled release/removal.',
    hazards: 'Collapse|Overload|Premature removal|Foundation failure|Unapproved modification',
    controls: 'Design verification, hold points, competent erection, exclusion and inspection before loading.',
    inspection: 'Inspect before loading, after changes, impact, weather or other events affecting stability.',
    stop: 'Stop for missing design/approval, damaged support, unexpected movement, overload or unauthorised modification.',
    responsibilities: 'Temporary works coordinator/designers control design; supervisors control erection and use.',
    worker: 'Do not modify or remove supports without authorisation; report movement or defects.',
    emergency: 'Evacuate the affected area and prevent entry until stability is assessed by competent persons.',
    example: 'A prop is found displaced before concrete loading; the pour is stopped and the support system is corrected and re-inspected.',
    learning: 'DESIGN → APPROVE → ERECT → INSPECT → LOAD → MONITOR → RELEASE',
  ),
  'dubai_heat_stress': _makeTopic(
    title: 'Heat Stress Management',
    intro: 'Controls for heat exposure, dehydration and heat-related illness during construction work in hot and humid conditions.',
    types: 'Outdoor work|High radiant heat|Heavy physical work|Heat-acclimatisation period',
    components: 'Cool drinking water|Shade|Ventilation|Rest area|Heat monitoring|Buddy system',
    requirements: 'Use risk-based heat controls, hydration, shade, work/rest adjustments, acclimatisation and worker monitoring.',
    hazards: 'Heat exhaustion|Heat stroke|Dehydration|Reduced concentration|Medication-related vulnerability',
    controls: 'Schedule heavy work appropriately, provide water/shade, monitor workers and use heat-stress procedures.',
    inspection: 'Monitor environmental conditions, work intensity, worker condition and effectiveness of controls.',
    stop: 'Stop or modify work when heat controls are inadequate or a worker shows signs of heat illness.',
    responsibilities: 'Management provides resources; supervisors monitor; workers use hydration/rest arrangements and report symptoms.',
    worker: 'Drink water, use rest/shade, report symptoms early and look after co-workers.',
    emergency: 'Move affected worker to a cool area, call medical support and follow emergency/first-aid procedures; suspected heat stroke is an emergency.',
    example: 'A worker becomes confused and collapses; work stops and emergency medical response is activated immediately.',
    learning: 'HYDRATE → SHADE → REST → MONITOR → RESPOND',
  ),
  'dubai_occupational_health': _makeTopic(
    title: 'Occupational Health',
    intro: 'Workplace health controls covering exposure assessment, fitness, surveillance, hygiene and prevention of work-related illness.',
    types: 'Health surveillance|Exposure control|Fitness to work|Ergonomics|Occupational hygiene',
    components: 'Exposure assessment|Medical surveillance|Hygiene facilities|Ergonomic controls|Health records',
    requirements: 'Identify health hazards and apply engineering/administrative controls, surveillance and worker information appropriate to exposure.',
    hazards: 'Dust/fumes|Noise|Vibration|Manual handling|Chemical exposure|Poor welfare',
    controls: 'Source control, ventilation, substitution, PPE, hygiene, health surveillance and early reporting.',
    inspection: 'Inspect exposure controls and welfare; review monitoring results and health trends where applicable.',
    stop: 'Stop or restrict exposure when control systems fail or an acute health hazard is uncontrolled.',
    responsibilities: 'Occupational health professionals advise; management implements controls; supervisors monitor work practices.',
    worker: 'Use controls and PPE, follow hygiene arrangements and report symptoms or exposure events.',
    emergency: 'Remove person from exposure, provide first aid/medical support and preserve exposure information for follow-up.',
    example: 'Noise monitoring shows a high exposure trend; engineering controls and hearing protection requirements are strengthened.',
    learning: 'IDENTIFY → CONTROL EXPOSURE → MONITOR HEALTH → IMPROVE',
  ),
  'dubai_ppe': _makeTopic(
    title: 'Personal Protective Equipment',
    intro: 'Selection, provision, use, inspection and maintenance of PPE as the final layer of protection after higher-level controls.',
    types: 'Head protection|Eye/face protection|Hearing protection|Hand protection|Foot protection|Protective clothing|Fall protection',
    components: 'Helmet|Safety glasses|Face shield|Gloves|Safety footwear|Hearing protection|Harness',
    requirements: 'Select PPE from risk assessment, ensure compatibility and fit, train users and maintain/replace damaged equipment.',
    hazards: 'Wrong PPE|Poor fit|Damaged PPE|Incompatibility|False sense of security',
    controls: 'Task-specific selection, fit checks, inspection, hygiene, storage and replacement.',
    inspection: 'Inspect before use and after contamination/damage; verify suitability for the task and other PPE.',
    stop: 'Stop the task when required PPE is missing, damaged, unsuitable or incompatible with the hazard.',
    responsibilities: 'Management provides suitable PPE; supervisors enforce use; workers maintain and report defects.',
    worker: 'Wear required PPE correctly and never modify protective equipment.',
    emergency: 'Provide first aid and emergency response while maintaining scene safety; PPE failure is reported and investigated.',
    example: 'A worker has eye protection that does not seal against the task hazard; the task pauses until suitable protection is provided.',
    learning: 'ASSESS → SELECT → FIT → USE → INSPECT → REPLACE',
  ),
  'dubai_emergency': _makeTopic(
    title: 'Emergency Preparedness & Response',
    intro: 'Planning and readiness for fires, medical events, rescue, severe weather, spills and other site emergencies.',
    types: 'Fire emergency|Medical emergency|Rescue|Spill / release|Severe weather',
    components: 'Emergency plan|Alarm|Muster point|Emergency contact|First-aid kit|Rescue equipment',
    requirements: 'Define scenarios, alarms, roles, communication, evacuation, rescue, medical support, muster and recovery.',
    hazards: 'Delayed response|Blocked escape|Poor communication|Untrained responders|Secondary exposure',
    controls: 'Drills, clear routes, signage, trained responders, emergency equipment and regular plan review.',
    inspection: 'Inspect alarms, routes, exits, muster points, emergency equipment and contact information.',
    stop: 'Stop work when emergency readiness is compromised or an active emergency exists.',
    responsibilities: 'Emergency controller coordinates; supervisors account for people; trained responders perform assigned roles.',
    worker: 'Know alarm signals, routes and muster point; follow instructions and do not re-enter without authorisation.',
    emergency: 'Raise alarm, call emergency services, evacuate/account for people and provide trained assistance only.',
    example: 'A fire alarm activates during lifting; the lift is secured if safe and personnel move to the muster point.',
    learning: 'ALARM → STOP → EVACUATE → ACCOUNT → RESPOND → RECOVER',
  ),
  'dubai_incident': _makeTopic(
    title: 'Incident Reporting & Investigation',
    intro: 'A structured process for reporting incidents, near misses and unsafe events, preserving evidence, finding causes and preventing recurrence.',
    types: 'Incident|Near miss|Property damage|Environmental event|Unsafe condition',
    components: 'Initial notification|Scene preservation|Evidence|Root-cause analysis|Corrective action|Close-out',
    requirements: 'Report promptly, protect people, preserve evidence, investigate proportionately and verify corrective actions.',
    hazards: 'Delayed reporting|Evidence loss|Blame focus|Weak root cause|Repeat events',
    controls: 'Immediate notification, scene control, evidence collection, causal analysis and action effectiveness checks.',
    inspection: 'Review incident records, actions, trends and evidence quality.',
    stop: 'Stop affected work when a serious event or uncontrolled hazard remains.',
    responsibilities: 'Management ensures reporting and resources; investigators establish facts; HSE coordinates learning.',
    worker: 'Report events promptly and honestly; do not disturb evidence unless needed for safety.',
    emergency: 'Treat casualties, secure scene, notify emergency services and preserve evidence.',
    example: 'A near miss occurs when a load passes over a work area; the lift is stopped and the investigation identifies a failed exclusion control.',
    learning: 'REPORT → SECURE → INVESTIGATE → CORRECT → VERIFY → LEARN',
  ),
  'dubai_contractor': _makeTopic(
    title: 'Contractor & Subcontractor HSE Management',
    intro: 'Controls for selecting, onboarding, supervising and monitoring contractors and subcontractors so site HSE requirements remain consistent.',
    types: 'Prequalification|Mobilisation|Performance monitoring|Interface management',
    components: 'Contractor HSE plan|Competence records|Induction|Permit|Inspection|Performance review',
    requirements: 'Assess capability before award, define requirements, verify competence and monitor performance throughout the contract.',
    hazards: 'Competence gap|Conflicting procedures|Poor supervision|Interface failure|Weak action closure',
    controls: 'Prequalification, induction, coordination, audits, field inspections and performance reviews.',
    inspection: 'Verify documentation and field performance, including subcontractor interfaces.',
    stop: 'Stop contractor work for serious uncontrolled risk, missing competence or failure to meet critical controls.',
    responsibilities: 'Principal contractor coordinates; subcontractor manages its workers; HSE verifies compliance.',
    worker: 'Follow host-site rules and report hazards or conflicts between procedures.',
    emergency: 'Use site emergency arrangements and ensure contractor personnel are accounted for.',
    example: 'A subcontractor starts hot work without the required permit; the work stops and the contractor is re-briefed before authorisation.',
    learning: 'SELECT → INDUCT → CONTROL → MONITOR → IMPROVE',
  ),
  'dubai_environment': _makeTopic(
    title: 'Environmental & Waste Management',
    intro: 'Construction controls for waste, spills, dust, noise, water, emissions and environmental interfaces.',
    types: 'Waste segregation|Hazardous waste|Spill prevention|Dust control|Noise control',
    components: 'Waste containers|Labels|Spill kit|Bund / secondary containment|Dust suppression|Waste records',
    requirements: 'Identify environmental aspects, segregate waste, control releases and manage storage/transport/disposal through approved arrangements.',
    hazards: 'Spill|Uncontrolled waste|Dust|Noise|Contaminated water|Poor storage',
    controls: 'Segregation, containment, housekeeping, dust suppression, spill readiness and monitoring.',
    inspection: 'Inspect waste areas, containers, labels, spill controls and environmental interfaces.',
    stop: 'Stop activities causing an uncontrolled release, unsafe waste handling or significant environmental exposure.',
    responsibilities: 'Site management controls resources; environmental/HSE personnel monitor; workers prevent releases.',
    worker: 'Segregate waste correctly, use spill controls and report releases immediately.',
    emergency: 'Stop source if safe, contain, protect drains, raise alarm and follow spill response arrangements.',
    example: 'A hydraulic leak occurs from plant; the area is isolated and a spill kit is used to prevent migration to a drain.',
    learning: 'PREVENT → CONTAIN → SEGREGATE → RECORD → IMPROVE',
  ),
  'dubai_inspection': _makeTopic(
    title: 'HSE Inspection & Audit',
    intro: 'Planned verification of workplace conditions, systems and controls to identify gaps and confirm effective implementation.',
    types: 'Routine inspection|Thematic inspection|Management walkdown|System audit',
    components: 'Checklist|Finding|Action|Owner|Due date|Verification evidence',
    requirements: 'Use risk-based inspection planning, competent inspectors, objective evidence and action tracking.',
    hazards: 'Superficial inspection|Missed critical controls|Late actions|Repeat findings',
    controls: 'Inspect field conditions, interview workers, review evidence and verify closure effectiveness.',
    inspection: 'Check critical controls at the workface and trend recurring findings.',
    stop: 'Stop affected work when a critical unsafe condition is identified.',
    responsibilities: 'Inspectors identify evidence; owners correct; HSE verifies closure.',
    worker: 'Support inspections, provide accurate information and correct assigned actions.',
    emergency: 'If an inspection identifies an emergency hazard, make the area safe immediately before continuing the audit.',
    example: 'A management walkdown finds an open excavation without a barrier; work stops and the barrier is restored before restart.',
    learning: 'OBSERVE → RECORD → CORRECT → VERIFY → TREND',
  ),
  'dubai_performance': _makeTopic(
    title: 'HSE Performance Monitoring',
    intro: 'Measurement and review of leading and lagging indicators to understand HSE performance and drive improvement.',
    types: 'Leading indicators|Lagging indicators|KPI dashboard|Trend analysis',
    components: 'Inspection KPI|Training KPI|Near-miss trend|Incident rate|Action closure|Audit score',
    requirements: 'Use meaningful indicators, reliable data, trend analysis and management review rather than numbers alone.',
    hazards: 'Poor data quality|Target gaming|Delayed actions|Weak learning',
    controls: 'Combine proactive and reactive indicators, verify data and focus on significant risks.',
    inspection: 'Review trends, recurring failures, overdue actions and effectiveness of interventions.',
    stop: 'Escalate or stop work when performance signals a serious uncontrolled risk.',
    responsibilities: 'Management reviews performance; HSE analyses; supervisors act on field trends.',
    worker: 'Participate honestly in reporting and action closure.',
    emergency: 'Use performance data during post-event review and restart decisions.',
    example: 'Repeated overdue scaffold actions trigger a focused review and increased field verification.',
    learning: 'MEASURE → ANALYSE → ACT → VERIFY → IMPROVE',
  ),
  'dubai_building_code': _makeTopic(
    title: 'Dubai Building Code & Safety',
    intro: 'Reference to Dubai building requirements that establish minimum health, safety, welfare and environmental expectations for buildings and construction interfaces.',
    types: 'Building design compliance|Structural safety|Fire/life safety interface|Accessibility / welfare',
    components: 'Approved drawings|Specifications|Structural system|Fire systems|Safety provisions|Inspection records',
    requirements: 'Use current approved code requirements, approved designs and authority processes applicable to the project.',
    hazards: 'Non-compliant design|Unapproved change|Structural defect|Life-safety deficiency',
    controls: 'Design review, approval control, inspection, change management and competent engineering oversight.',
    inspection: 'Verify construction against approved drawings/specifications and record deviations for resolution.',
    stop: 'Stop affected work where a safety-critical deviation or unapproved change could compromise building safety.',
    responsibilities: 'Designers/engineers own design compliance; contractors build to approved information; HSE verifies field safety interfaces.',
    worker: 'Do not alter safety-critical building systems without authorisation; report defects.',
    emergency: 'Secure affected area and escalate structural/fire/life-safety concerns immediately.',
    example: 'A site team proposes an unapproved opening in a structural element; work stops until engineering review and approval.',
    learning: 'APPROVED DESIGN → BUILD → INSPECT → VERIFY → HANDOVER',
  ),
  'dubai_permit_to_work': _makeTopic(
    title: 'Permit to Work System',
    intro: 'A formal authorisation process used to control specified high-risk work and confirm critical precautions before exposure.',
    types: 'Hot work permit|Confined space permit|Electrical isolation|Excavation permit|Lifting / special permit',
    components: 'Permit issuer|Permit receiver|Isolation certificate|Gas test|Attachments|Handover',
    requirements: 'Define scope, hazards, isolations, precautions, validity, responsible persons and close-out requirements.',
    hazards: 'Wrong scope|Expired permit|Missing isolation|Permit bypass|Poor handover',
    controls: 'Field verification before issue, clear display, controlled suspension/revalidation and formal close-out.',
    inspection: 'Check permit conditions against actual work and revalidate after changes or interruptions.',
    stop: 'Stop work when permit is absent, expired, invalid for actual conditions or critical precautions are missing.',
    responsibilities: 'Issuer authorises; receiver implements; supervisors monitor; HSE audits the system.',
    worker: 'Understand permit limits and stop when conditions differ from the permit.',
    emergency: 'Suspend permit, make area safe and follow emergency procedures.',
    example: 'Excavation scope changes location; the permit is suspended and reissued after reassessment and service verification.',
    learning: 'SCOPE → ISOLATE → VERIFY → AUTHORISE → WORK → CLOSE',
  ),
  'dubai_cop_site_establishment': _makeTopic(
    title: 'Code of Practice: Site Establishment & General Arrangements',
    intro: 'Controls for establishing a construction site so access, welfare, storage, work zones, utilities and general arrangements are safe from mobilisation onward.',
    types: 'Site mobilisation|Layout planning|Temporary facilities|Access arrangements',
    components: 'Site layout|Fencing|Gate|Welfare area|Temporary utilities|Emergency access',
    requirements: 'Plan site layout around safe access, emergency routes, welfare, storage, traffic and work interfaces.',
    hazards: 'Poor layout|Blocked emergency route|Unsafe utilities|Public intrusion|Congestion',
    controls: 'Segregation, housekeeping, controlled access, emergency access and regular layout review.',
    inspection: 'Inspect site boundaries, routes, facilities, utilities and changes in layout.',
    stop: 'Stop when emergency access is blocked, boundaries fail or site arrangements create immediate serious risk.',
    responsibilities: 'Site manager owns layout; HSE verifies; supervisors maintain work areas.',
    worker: 'Use designated routes and facilities and report damaged barriers or blocked access.',
    emergency: 'Maintain emergency access and evacuate according to the site plan.',
    example: 'A new delivery area blocks an emergency route; deliveries are moved and the route is restored.',
    learning: 'LAYOUT → ACCESS → SEGREGATE → MAINTAIN → REVIEW',
  ),
  'dubai_cop_public_protection': _makeTopic(
    title: 'Code of Practice: Site Security & Public Protection',
    intro: 'Controls to protect the public, visitors and neighbouring properties from construction hazards.',
    types: 'Perimeter protection|Public interface|Pedestrian diversion|Overhead protection',
    components: 'Fence|Gate|Barrier|Warning sign|Covered walkway|Security control',
    requirements: 'Prevent unauthorised entry, protect public routes and control falling-object, vehicle and workface exposure.',
    hazards: 'Public intrusion|Vehicle strike|Falling objects|Open excavation|Poor signage',
    controls: 'Secure boundaries, controlled gates, protected walkways, signage and continuous monitoring.',
    inspection: 'Inspect perimeter, barriers, signs and public interfaces, especially after changes.',
    stop: 'Stop work where public protection is compromised or uncontrolled access exists.',
    responsibilities: 'Site management controls security; supervisors control work near public interfaces.',
    worker: 'Do not open barriers or allow unauthorised access.',
    emergency: 'Protect the public first, raise alarm and coordinate emergency services if an incident occurs.',
    example: 'A pedestrian route is affected by façade work; the route is segregated and protected before work continues.',
    learning: 'SECURE → SEPARATE → SIGN → PROTECT → MONITOR',
  ),
  'dubai_cop_access_housekeeping': _makeTopic(
    title: 'Code of Practice: Access, Egress & Housekeeping',
    intro: 'Requirements for safe movement, clear routes, orderly work areas and emergency egress.',
    types: 'Pedestrian access|Emergency egress|Stair access|Housekeeping zones',
    components: 'Walkway|Stair|Handrail|Lighting|Housekeeping point|Access gate',
    requirements: 'Keep routes stable, clear, illuminated and suitable for the task and emergency use.',
    hazards: 'Trips|Falls|Blocked exits|Poor lighting|Falling materials',
    controls: 'Routine housekeeping, route inspection, material control and prompt removal of obstructions.',
    inspection: 'Check access routes, stairs, handrails, lighting and egress before and during work.',
    stop: 'Stop affected work when a critical route or emergency exit is blocked or unsafe.',
    responsibilities: 'Supervisors maintain routes; workers keep areas orderly; HSE verifies.',
    worker: 'Keep access clear, use designated routes and report defects.',
    emergency: 'Maintain a clear evacuation path and guide people to safe assembly areas.',
    example: 'Materials are stacked in an emergency exit route; work in the area stops until the route is cleared.',
    learning: 'CLEAR → LIGHT → SEGREGATE → INSPECT → EXIT',
  ),
  'dubai_cop_welfare_facilities': _makeTopic(
    title: 'Code of Practice: Worker Welfare & Site Facilities',
    intro: 'Site arrangements that support worker welfare, hygiene, rest, drinking water, sanitation and suitable facilities.',
    types: 'Welfare facilities|Drinking water|Sanitation|Rest areas|Changing facilities',
    components: 'Water point|Toilet|Wash station|Rest shelter|First-aid facility|Waste bins',
    requirements: 'Provide suitable facilities, maintain hygiene and ensure access appropriate to workforce size and site conditions.',
    hazards: 'Heat exposure|Poor hygiene|Contamination|Inadequate facilities|Dehydration',
    controls: 'Clean facilities, cool drinking water, shaded/rest areas and inspection/maintenance arrangements.',
    inspection: 'Inspect availability, cleanliness, water, sanitation and welfare condition.',
    stop: 'Stop work or escalate where welfare failure creates serious health risk, especially during heat conditions.',
    responsibilities: 'Management provides resources; supervisors ensure access; workers maintain hygiene.',
    worker: 'Use facilities responsibly and report shortages or contamination.',
    emergency: 'Treat illness, provide first aid and escalate medical needs.',
    example: 'Drinking water supply is interrupted during hot work; the activity is paused until adequate water and welfare controls are restored.',
    learning: 'WATER → SHADE → HYGIENE → REST → REPORT',
  ),
  'dubai_cop_material_storage': _makeTopic(
    title: 'Code of Practice: Material Storage & Handling',
    intro: 'Safe storage, stacking, movement and handling of construction materials to prevent collapse, struck-by injuries, fire and manual-handling harm.',
    types: 'General storage|Hazardous storage|Long materials|Gas cylinders|Material handling',
    components: 'Rack|Pallet|Chock|Barrier|Label|Storage zone',
    requirements: 'Plan stable storage, load limits, access, segregation, compatibility and handling methods.',
    hazards: 'Falling materials|Stack collapse|Manual handling|Cylinder release|Blocked access',
    controls: 'Stable stacking, restraint, segregation, clear aisles, mechanical aids and inspection.',
    inspection: 'Check stacks, racks, pallets, labels, access and storage conditions.',
    stop: 'Stop unsafe storage where collapse, falling-object or incompatible-storage risk exists.',
    responsibilities: 'Storekeeper/supervisor controls; workers use approved handling methods.',
    worker: 'Do not climb unstable stacks or remove restraints without control.',
    emergency: 'Isolate the area after collapse/shift and use trained response arrangements.',
    example: 'A pallet stack becomes unstable; access is isolated and materials are safely restacked before work continues.',
    learning: 'PLAN → STORE → SECURE → ACCESS → INSPECT',
  ),
  'dubai_cop_formwork_falsework': _makeTopic(
    title: 'Code of Practice: Formwork, Falsework & Temporary Support',
    intro: 'Controls for temporary support systems used to carry concrete, construction loads and temporary stability demands.',
    types: 'Formwork|Falsework|Props|Shoring|Table forms',
    components: 'Formwork panel|Prop|Bearer|Brace|Tie|Sole support',
    requirements: 'Use approved design, correct erection sequence, load limits, stability and inspection before loading.',
    hazards: 'Collapse|Overload|Premature striking|Falling components|Poor support',
    controls: 'Design verification, controlled erection, exclusion zones, inspections and authorised striking sequence.',
    inspection: 'Inspect supports, connections, foundations, alignment and changes before loading and striking.',
    stop: 'Stop for damaged/displaced support, missing bracing, overloading or unauthorised striking.',
    responsibilities: 'Temporary works/design team controls design; supervisors control erection and striking.',
    worker: 'Do not remove supports or enter exclusion zones without authorisation.',
    emergency: 'Evacuate the affected area and prevent access until stability is assessed.',
    example: 'A prop is displaced before a slab pour; the pour stops until the support system is corrected and verified.',
    learning: 'DESIGN → ERECT → BRACE → INSPECT → LOAD → STRIKE',
  ),
  'dubai_cop_rebar_concrete': _makeTopic(
    title: 'Code of Practice: Reinforcement, Concrete & Construction Operations',
    intro: 'Controls for reinforcement fixing, concrete placement, pumping, vibrating and associated construction activities.',
    types: 'Rebar fixing|Concrete pouring|Pump operation|Vibration|Formwork interface',
    components: 'Rebar cage|Coupler|Concrete pump|Hose|Vibrator|Edge protection',
    requirements: 'Coordinate reinforcement, formwork, lifting, access, pump setup and pour sequence.',
    hazards: 'Impaling|Hose whip|Formwork failure|Struck-by|Falls|Cement exposure',
    controls: 'Cap/protect protruding steel, secure hoses, control pump setup, maintain edge protection and communication.',
    inspection: 'Inspect formwork readiness, rebar protection, pump lines, access and exclusion zones.',
    stop: 'Stop for unstable formwork, uncontrolled pump line, exposed impalement hazard or unsafe access.',
    responsibilities: 'Pour supervisor coordinates; competent operators manage plant; HSE verifies controls.',
    worker: 'Follow pour instructions, stay clear of moving hoses and report defects.',
    emergency: 'Stop pump safely, isolate energy and provide first aid/emergency response.',
    example: 'A pump hose begins to move unexpectedly; the pour is stopped and the line/control arrangement is checked before restart.',
    learning: 'PROTECT → SET UP → COMMUNICATE → POUR → MONITOR → FINISH',
  ),
  'dubai_cop_machinery_guarding': _makeTopic(
    title: 'Code of Practice: Plant, Machinery & Guarding',
    intro: 'Controls for machinery selection, guarding, isolation, operation and maintenance to prevent contact with moving parts and stored energy.',
    types: 'Fixed machinery|Portable machinery|Powered tools|Maintenance / isolation',
    components: 'Guard|Emergency stop|Interlock|Isolation point|LOTO device|Operator control',
    requirements: 'Use suitable guarded equipment, competent operators, isolation for maintenance and controlled access.',
    hazards: 'Entanglement|Crushing|Cutting|Unexpected start|Ejection|Stored energy',
    controls: 'Guards, interlocks, LOTO, safe operating procedures and maintenance controls.',
    inspection: 'Inspect guards, controls, cables, emergency stops and isolation arrangements.',
    stop: 'Stop for missing guard, failed interlock, unexpected movement or unsafe maintenance condition.',
    responsibilities: 'Competent operators use equipment; maintenance controls isolation; supervisors verify.',
    worker: 'Never bypass guards or reach into moving machinery; isolate before intervention.',
    emergency: 'Isolate energy before rescue/first aid where necessary and call emergency support.',
    example: 'A machine guard is removed for adjustment; the machine is isolated and the guard restored before operation.',
    learning: 'GUARD → ISOLATE → TEST → OPERATE → MAINTAIN',
  ),
  'dubai_cop_ladders_mobile_towers': _makeTopic(
    title: 'Code of Practice: Ladders & Mobile Access Towers',
    intro: 'Controls for ladder selection/use and mobile access tower setup, movement, access and stability.',
    types: 'Ladder|Step ladder|Extension ladder|Mobile access tower',
    components: 'Ladder feet|Stabiliser|Platform|Guardrail|Toe board|Castor lock',
    requirements: 'Select the right access system, stable setup, safe access and compliance with manufacturer/system requirements.',
    hazards: 'Falls|Overreaching|Tower movement|Overturning|Defective ladder',
    controls: 'Stable base, correct angle/setup where applicable, locked castors, edge protection and safe movement rules.',
    inspection: 'Inspect ladder/tower condition, base, access, guardrails, platforms and wheels before use.',
    stop: 'Stop for damaged equipment, unstable base, unlocked castors, unsafe height/configuration or poor weather.',
    responsibilities: 'Competent persons set up/inspect where required; users follow system instructions.',
    worker: 'Do not move a mobile tower with people on it; maintain safe climbing and avoid overreaching.',
    emergency: 'Secure the equipment and respond through site emergency arrangements after a fall or instability event.',
    example: 'A mobile tower is found with one castor unlocked; access is stopped until the tower is correctly secured and checked.',
    learning: 'SELECT → SET → LOCK → ACCESS → WORK → CHECK',
  ),
  'dubai_cop_fire_emergency': _makeTopic(
    title: 'Code of Practice: Fire Prevention & Emergency Arrangements',
    intro: 'Construction fire prevention, emergency access, alarm, evacuation and firefighting readiness.',
    types: 'Fire prevention|Hot work control|Emergency evacuation|Fire response',
    components: 'Alarm|Extinguisher|Fire point|Muster point|Emergency route|Fire watch',
    requirements: 'Control ignition sources, combustibles, temporary services and emergency routes; maintain response readiness.',
    hazards: 'Fire|Smoke|Explosion|Blocked escape|Delayed response',
    controls: 'Housekeeping, hot-work control, extinguishers, alarms, clear routes and drills.',
    inspection: 'Inspect fire points, extinguishers, alarms, routes and hot-work controls.',
    stop: 'Stop hot work or affected activities when fire controls are missing or escape routes are compromised.',
    responsibilities: 'Site management maintains fire arrangements; supervisors enforce; trained responders assist.',
    worker: 'Know alarm/muster arrangements and never block emergency equipment.',
    emergency: 'Raise alarm, evacuate, account for people and use firefighting equipment only if trained and safe.',
    example: 'Combustible waste accumulates near a hot-work area; hot work stops until the area is cleared and fire controls restored.',
    learning: 'PREVENT → ALARM → EVACUATE → ACCOUNT → RESPOND',
  ),
  'dubai_cop_signs_barricading': _makeTopic(
    title: 'Code of Practice: Safety Signs, Barricading & Exclusion Zones',
    intro: 'Controls for communicating hazards and preventing entry into dangerous work areas.',
    types: 'Warning signs|Mandatory signs|Prohibition signs|Barricaded zones|Exclusion zones',
    components: 'Barrier|Sign|Gate|Warning light|Tag|Physical protection',
    requirements: 'Signs must be visible, understandable, correctly located and supported by physical barriers where needed.',
    hazards: 'Unauthorised entry|Poor visibility|Barrier bypass|Public exposure|Struck-by',
    controls: 'Physical segregation, clear signs, lighting and routine checks.',
    inspection: 'Inspect signs, barriers, gates, lights and zone boundaries as work changes.',
    stop: 'Stop work where critical exclusion cannot be maintained or people are exposed.',
    responsibilities: 'Supervisors define zones; workers maintain them; HSE verifies.',
    worker: 'Respect signs and barriers; never cross without authorisation.',
    emergency: 'Secure the zone, control access and raise alarm after an intrusion/incident.',
    example: 'A lifting exclusion zone is breached; the lift is paused and the boundary is restored before continuing.',
    learning: 'IDENTIFY → BARRICADE → SIGN → CONTROL → VERIFY',
  ),
  'dubai_cop_lighting_weather': _makeTopic(
    title: 'Code of Practice: Construction Lighting, Weather & Visibility',
    intro: 'Controls for lighting, visibility, wind, dust, heat and other environmental conditions that affect safe construction work.',
    types: 'Day work|Night work|Poor visibility|High wind|Dust / sand|Weather shutdown',
    components: 'Lighting tower|Task light|Emergency light|Wind monitoring|Visibility check|Reflective marking',
    requirements: 'Provide adequate illumination, monitor conditions and apply task/equipment limits and shutdown criteria.',
    hazards: 'Poor visibility|Wind loading|Heat stress|Dust|Slippery conditions|Reduced communication',
    controls: 'Adequate lighting, weather monitoring, secure loose materials, reflective marking and work adjustment.',
    inspection: 'Inspect lighting, weather-sensitive equipment, routes, barriers and visibility before and during work.',
    stop: 'Stop when visibility, wind, dust or other conditions make the approved task unsafe.',
    responsibilities: 'Supervisors monitor conditions; competent operators follow equipment limits; HSE verifies.',
    worker: 'Report deteriorating conditions and follow shutdown instructions.',
    emergency: 'Stop activity, secure equipment/materials and move people to safe areas as required.',
    example: 'Visibility falls during a dust event; lifting is suspended and equipment/materials are secured before conditions are reassessed.',
    learning: 'CHECK WEATHER → LIGHT → SECURE → WORK → MONITOR → STOP',
  ),
};

_TopicData _makeTopic({required String title, required String intro, required String types, required String components, required String requirements, required String hazards, required String controls, required String inspection, required String stop, required String responsibilities, required String worker, required String emergency, required String example, required String learning}) {
  final t = types.split('|');
  final c = components.split('|');
  final sections = <String, List<_DetailItem>>{
    'Purpose & Scope': [
      _DetailItem(title: 'Purpose', detail: 'Apply professional HSE controls to $title across planning, execution, supervision, inspection and close-out.'),
      _DetailItem(title: 'Scope', detail: 'Covers employees, contractors, subcontractors, visitors, equipment and work interfaces relevant to $title.'),
    ],
    'Technical Requirements': [
      _DetailItem(title: 'Core requirement', detail: requirements),
      _DetailItem(title: 'Competence & approval', detail: 'Use competent persons and approved methods, designs, permits or equipment instructions applicable to $title.'),
      _DetailItem(title: 'Change control', detail: 'Reassess when the work sequence, equipment, environment or interfaces change.'),
    ],
    'Main Hazards': [
      _DetailItem(title: 'Primary hazards', detail: hazards),
      _DetailItem(title: 'Interface risk', detail: 'Consider people, plant, access, public interfaces, temporary works and simultaneous operations.'),
      _DetailItem(title: 'Human factors', detail: 'Fatigue, communication, competence and procedural drift can weaken otherwise good controls.'),
    ],
    'Safety Controls': [
      _DetailItem(title: 'Control measures', detail: controls),
      _DetailItem(title: 'Field verification', detail: 'Verify that the planned controls are physically present and effective before exposure.'),
      _DetailItem(title: 'Communication', detail: 'Brief affected personnel and coordinate interfaces before starting or changing the task.'),
    ],
    'Inspection & Verification': [
      _DetailItem(title: 'Pre-start check', detail: inspection),
      _DetailItem(title: 'Ongoing checks', detail: 'Repeat checks after changes, abnormal events, weather impacts, interruptions or reported defects.'),
      _DetailItem(title: 'Close-out', detail: 'Record findings, assign actions and verify effectiveness before closure.'),
    ],
    'Stop-Work Conditions': [
      _DetailItem(title: 'STOP', detail: stop),
      _DetailItem(title: 'Escalate', detail: 'Notify the supervisor/HSE and secure the affected area when a critical barrier fails.'),
      _DetailItem(title: 'Restart', detail: 'Resume only after the hazard is controlled, required approvals are restored and field verification is complete.'),
    ],
    'Responsibilities': [
      _DetailItem(title: 'Management / HSE', detail: responsibilities),
      _DetailItem(title: 'Supervisor / competent person', detail: 'Control the workface, verify critical controls and intervene when conditions are unsafe.'),
      _DetailItem(title: 'Contractor interface', detail: 'Coordinate responsibilities and ensure subcontractor controls align with the project system.'),
    ],
    'Worker Responsibilities': [
      _DetailItem(title: 'Work to the method', detail: worker),
      _DetailItem(title: 'Report and intervene', detail: 'Report hazards, defects, near misses and changed conditions immediately; use stop-work authority where required.'),
      _DetailItem(title: 'Protect others', detail: 'Maintain housekeeping, segregation and safe behaviour around shared work areas.'),
    ],
    'Emergency Response': [
      _DetailItem(title: 'Immediate action', detail: emergency),
      _DetailItem(title: 'Rescue / medical', detail: 'Use the trained site emergency and rescue arrangements; do not create secondary casualties.'),
      _DetailItem(title: 'Recovery', detail: 'Preserve evidence, report the event and review controls before restart.'),
    ],
    'Practical Site Example': [
      _DetailItem(title: 'Scenario', detail: example),
      _DetailItem(title: 'HSE response', detail: 'STOP → ISOLATE/EXCLUDE → ASSESS → CORRECT → VERIFY → RESUME, using the controls applicable to the task.'),
    ],
    'Quick Learning Formula': [
      _DetailItem(title: 'Field formula', detail: learning),
      _DetailItem(title: 'Golden rule', detail: 'No exposure before critical controls are ready and verified.'),
    ],
  };
  return _TopicData(title: title, intro: intro, types: [for (final x in t) _DetailItem(title: x, detail: _typeDetail(title, x)], items: [for (final x in c) _DetailItem(title: x, detail: _componentDetail(title, x)], sections: sections);
}

String _typeDetail(String topic, String item) => '$item is a $topic work system or application. Select and use it only when it matches the task, risk assessment, approved method and applicable system/manufacturer requirements.');
String _componentDetail(String topic, String item) => '$item is a key component or control item for $topic. Check condition, suitability, compatibility, installation/use and inspection status before exposure.');

class DubaiHseTopicRouter { static Widget pageFor(ReferenceTopic topic) => DubaiHseDetailPage(topic: topic); }