// SafeNexus HSE — Emergency & Rescue Part 4 — Expanded Field Edition
// File: lib/data/emergency_rescue/emergency_rescue_part4.dart
//
// Topics 13–16: Road Traffic Rescue, Machinery Entrapment, Water Rescue,
// Heat Illness and Environmental Exposure.
// Educational field guidance. Follow the current site ERP, approved rescue
// plans, competent-person direction, equipment instructions, SDS where relevant,
// applicable UAE/Emirate requirements, and emergency-service command.

import 'emergency_rescue_part1.dart';

const List<EmergencyRescueTopic> emergencyRescuePart4 = <EmergencyRescueTopic>[
  EmergencyRescueTopic(
    id: 'ER-13',
    title: 'Vehicle & Road Traffic Incident Rescue',
    purpose:
        'Vehicle and road traffic incident rescue is the coordinated response to a collision, rollover, struck-by event, vehicle fire, pedestrian impact, or person trapped in or beneath a vehicle. The priorities are scene safety, early alarm, prevention of secondary collisions, rapid access to professional medical care, and controlled casualty movement. Untrained personnel must not attempt technical vehicle extrication or enter an unstable traffic scene.',
    scope:
        'Applies to construction-site roads, public-road interfaces, haul routes, logistics yards, parking areas, reversing zones, buses, light vehicles, forklifts, dump trucks, mobile plant and transport operations. Adapt the response to traffic speed, road geometry, visibility, load stability, vehicle energy sources, weather, nearby utilities, and access for ambulance/fire-rescue services.',
    keyKnowledge: <String>[
      'Recognize incident types: vehicle-to-vehicle collision, vehicle-pedestrian impact, rollover, run-over, reversing incident, load shift, vehicle fire, fuel or battery release, and entrapment. More than one hazard may exist at the same time.',
      'The first arriving person should stop at a safe location, assess from a protected position, raise the alarm, provide exact location and access gate, and request the appropriate site emergency team and public emergency services through the approved contact route.',
      'Prevent secondary impact. Establish an exclusion zone using the site traffic emergency plan, safe upstream warning, traffic diversion, spotters and physical barriers where competent responders can place them safely. Do not stand in a live lane to direct traffic.',
      'Treat every involved vehicle as potentially unstable until assessed. Consider rolling, movement from damaged brakes, suspended loads, leaking fluids, damaged tyres, high-voltage hybrid/EV systems, airbags, pretensioners, compressed gas cylinders and stored energy.',
      'Do not move a casualty unless there is an immediate threat such as fire, explosion, or another danger that cannot be controlled, and movement can be performed without creating greater risk. Follow dispatcher, medic and rescue-team direction.',
      'Do not pull a trapped person, cut a seat belt without checking its load and casualty position, or operate damaged vehicle controls. Technical stabilization, glass management, cutting, spreading and lifting belong to trained rescue personnel using approved tools and methods.',
      'For suspected spinal injury, maintain the casualty in the position found when safe, support the head/neck without force, monitor breathing and responsiveness, control severe external bleeding within training, and avoid unnecessary movement.',
      'For vehicle fire, smoke, fuel leak, battery thermal event or hazardous cargo, withdraw, isolate the area, prevent ignition sources only when safe, and let trained fire/hazmat responders select tactics. Never approach a smoking or hissing high-voltage battery pack.',
      'Provide responders with vehicle type, number of casualties, entrapment status, fire/smoke, fuel or chemical release, traffic conditions, gate and route, and known hazards. Send a guide to meet responders without leaving the scene uncontrolled.',
      'Preserve evidence after life safety is addressed: protect the scene, record time and location, vehicle/equipment IDs, witnesses, photographs from safe positions, weather, traffic controls and initial actions. Do not delay rescue or medical care for investigation.',
      'After the event, suspend the affected route or activity until competent review confirms vehicle condition, road integrity, traffic controls, equipment inspection, operator authorization and corrective actions.',
      "Scene size-up should follow a deliberate sequence: safe approach, alarm, traffic control, casualty count, vehicle stability, fire/spill/electrical hazards, responder access, and a clear command handover. Reassess whenever traffic, weather, vehicle position or casualty condition changes.",
      "A vehicle can move after impact because of slope, damaged transmission, air suspension, unstable cargo or another vehicle pushing it. Keep people out of crush zones and do not rely on a dashboard indication or parking brake as proof of stability.",
      "For a suspected fuel or chemical release, avoid ignition sources and do not touch or walk through the liquid. Identify placards or cargo information only from a safe position; give responders the product/UN number if known, without approaching to investigate.",
      "For EV/hybrid incidents, identify the vehicle type from a safe distance when possible. Damaged orange high-voltage cables, battery smoke, hissing, popping, unusual heat or re-ignition risk require isolation and specialist fire response; do not cut high-voltage components.",
      "Casualty triage and treatment are medical functions. Site personnel should report the number and visible condition of casualties, protect the airway only within training, control major bleeding within competence, and follow the emergency dispatcher.",
      "A responder access route should be kept clear from the gate to the incident. Assign a guide at a safe rendezvous point, share gate codes/access restrictions through approved channels, and keep recovery vehicles separate from ambulance access.",
      "When a vehicle has contacted an overhead line, treat it and the surrounding ground as energized until the utility or competent electrical authority confirms otherwise. Keep people away, prevent approach, and follow the electrical emergency plan.",
      "Night or low-visibility response needs approved lighting that does not blind drivers, clear perimeter control, high-visibility PPE, and a protected working area. Hand signals alone are not a substitute for the site traffic plan.",
    ],
    siteImplementation: <String>[
      'Before work: include vehicle collision and pedestrian strike scenarios in the risk assessment and ERP; map ambulance access, gates, turning areas, safe responder staging and alternative routes.',
      'Maintain a current emergency contact method, site address/GPS reference, gate instructions, traffic-control arrangements, first-aid coverage and a process to summon external responders.',
      'Separate pedestrians and vehicles by engineered routes and barriers where practicable; use reversing controls, competent banksmen, speed management, lighting, visibility aids and controlled crossings based on risk assessment.',
      'Brief drivers and workers on alarm words, stop-traffic authority, safe refuge points, prohibition on entering live traffic, and how to report a collision or near miss.',
      'At an incident: raise alarm; stop nearby movement from a safe position; appoint an incident lead; isolate traffic; assess fire, spill, instability and electrical hazards; request medical/rescue support; account for people.',
      'Only trained responders stabilize a vehicle or conduct extrication. Confirm vehicle immobilization and energy isolation by competent responders, accounting for manufacturer-specific hazards and rescue equipment.',
      'First aiders provide care within competence, monitor airway/breathing/circulation, control life-threatening bleeding where trained, prevent heat loss/overheating as appropriate, and prepare a concise handover.',
      'Reopen the route only after incident command releases it and the responsible site authority confirms hazards, debris, damaged barriers, road surface and vehicle recovery are controlled.',
      'Complete incident reporting, witness statements, equipment checks, route risk reassessment, driver/operator review and close-out of corrective actions before restarting affected operations.',
      "Use a simple incident command log: time alarm received, caller, exact location, casualty count, hazards, resources requested, traffic closure, decisions, responder arrival and release authority.",
      "For a public-road interface, coordinate with the designated road/traffic authority and emergency services. Site staff must not make unauthorized lane closures or enter the carriageway.",
      "Before vehicle recovery, confirm casualty clearance, energy hazards, spill control, load stability, lifting/recovery method, exclusion zone and environmental protection. Use competent recovery personnel and suitable equipment.",
      "After a near miss or collision, review route layout, visibility, reversing, pedestrian segregation, driver competency, vehicle maintenance, fatigue/work scheduling and supervision—not only individual behavior.",
    ],
    practicalExample: <String>[
      'Scenario: a dump truck contacts a light vehicle at a site junction. One occupant is conscious but trapped; traffic is still approaching and fluid is visible beneath the truck.',
      'First action: stop at a protected position, raise the site alarm, provide the junction name and nearest gate, request ambulance and trained rescue support, and warn the traffic-control lead.',
      'Secure the wider area: stop or divert approaching vehicles using the approved plan; keep bystanders away; do not walk into moving traffic or stand between vehicles.',
      'Observe without touching: report casualty count, entrapment, fluid, smoke, vehicle position and any unstable load. Do not attempt to pull the occupant or move either vehicle.',
      'When trained responders arrive, brief them and transfer scene control. First aider approaches only when the route and vehicle are declared safe, then provides care within competence.',
      'After casualty transfer, preserve records and keep the junction closed until vehicle recovery, spill control and traffic-route inspection are authorized.',
      'Field checklist: alarm/location; ambulance/rescue requested; traffic isolated; secondary hazards identified; casualty count and access relayed; no unauthorized extrication; handover completed; scene release documented.',
      "Command handover example: 'One trapped casualty in the front passenger seat; no visible flame; fluid under engine bay; truck is on a slight slope; east gate is open; traffic stopped at Junction C; ambulance and technical rescue requested.'",
      "Do not promise a rescue time. Give responders accurate changing observations and let the incident commander decide the method and priorities.",
    ],
    stopWorkConditions: <String>[
      'Live traffic cannot be safely controlled, visibility is poor, or responders would be exposed to a secondary collision.',
      'Vehicle, load, ground, slope or nearby structure is unstable or may move unexpectedly.',
      'Fire, smoke, fuel leak, hazardous cargo, battery venting, electrical line contact or unknown energy source is present and not controlled by trained responders.',
      'A proposed action requires cutting, lifting, jacking, glass removal, vehicle movement or technical extrication beyond the team’s competence or approved plan.',
      'Emergency access is blocked, communications fail, or the incident commander cannot maintain a safe exclusion zone.',
    ],
    interviewQuestions: <String>[
      'Q: What are the first priorities after a site vehicle collision? A: Protect yourself and others, raise the alarm with precise location, prevent secondary traffic impact, identify immediate hazards, request appropriate rescue/medical help, and follow incident command.',
      'Q: Should a trapped casualty be pulled out quickly? A: Not by untrained personnel. Keep the scene safe, provide reassurance and care within competence, and let trained rescue/medical responders determine extrication unless an immediate uncontrollable threat requires emergency movement.',
      'Q: What hazards are specific to hybrid or electric vehicles? A: High-voltage components, damaged energy storage, delayed thermal events, stored energy and manufacturer-specific isolation requirements. Keep distance from signs of battery damage and defer to trained responders.',
      'Q: When can the road reopen? A: Only after incident command and the responsible site authority confirm casualties are transferred, hazards and recovery are controlled, and the route has been inspected and released.',
      "Q: What information should the first caller provide? A: Site/project name, exact location and gate, incident type, casualty count and condition, entrapment, fire/spill/electrical hazards, access restrictions, caller name and callback number.",
      "Q: What is the role of the HSE Officer? A: Raise/escalate the alarm, support safe scene control and communications, coordinate site resources under the ERP, preserve records, and avoid taking over specialist rescue or medical decisions.",
    ],
  ),
  EmergencyRescueTopic(
    id: 'ER-14',
    title: 'Machinery Entrapment & Industrial Equipment Rescue',
    purpose:
        'Machinery entrapment rescue addresses a person caught, crushed, drawn-in, pinned or trapped by moving or stored-energy equipment. The response must prevent further movement, isolate hazardous energy through an authorized process, obtain medical and technical rescue support, and release the casualty in a controlled manner. Improvised reversing, cutting, lifting or restarting can worsen injury or cause a second casualty.',
    scope:
        'Applies to conveyors, rollers, presses, mixers, crushers, cutting machines, workshop equipment, forklifts, mobile plant, rotating shafts, powered gates, hydraulic systems, pneumatic systems and automated production lines. The actual method depends on machine design, energy sources, load position, guarding, manufacturer instructions and competent rescue capability.',
    keyKnowledge: <String>[
      'Identify energy sources: electrical supply, batteries, hydraulic pressure, pneumatic pressure, gravity, springs, flywheels, rotating inertia, counterweights, suspended loads, thermal energy and process materials.',
      'Emergency stop is not necessarily energy isolation. Stop controls may halt motion but leave stored energy, automatic restart capability or hazardous voltage. Apply the site energy-control/LOTO process by authorized personnel.',
      'Never reverse, jog, reset, cycle, lift or lower equipment to free a casualty unless a competent rescue lead has assessed the machine and approved the action under a controlled plan.',
      'Prevent unauthorized restart: control the operating station, isolate and lock/tag as required, verify zero-energy state using the approved method, and account for all energy sources before intervention.',
      'Stored pressure must be relieved or mechanically restrained only by trained personnel using manufacturer-approved procedures. A hydraulic ram, suspended component or spring can move suddenly when pressure changes.',
      'Do not remove guards, cut machine frames, dismantle components or use a forklift/crane to pull a trapped person without engineering and rescue-team assessment. These actions can shift load paths or create crushing hazards.',
      'Assess casualty condition and entrapment mechanism: compression, crush injury, bleeding, amputation, burns, electrical contact, chemical exposure or restricted breathing. Request ambulance and specialist rescue early.',
      'Do not release prolonged compression without medical/rescue coordination. The casualty may need controlled release and immediate advanced medical support; first aiders must not delay emergency services while attempting complex treatment.',
      'If a limb is trapped, do not force it free or apply improvised traction. Protect from further movement, control visible bleeding within training, maintain communication and prepare for the responder’s release plan.',
      'Use a clear command structure: incident lead, machine/energy isolation authority, technical rescue lead, first aider/medic, perimeter controller and communications liaison. One person coordinates instructions.',
      'After rescue, retain isolation until the machine is inspected, damaged parts are secured, guards/interlocks are restored, cause is investigated and formal authorization is given to return to service.',
      "Apply a machine-specific energy inventory: normal supply, alternative feeds, control circuits, batteries, gravity, pressure accumulators, trapped product, thermal energy and automatic sequences. A single isolator may not control every source.",
      "A zero-energy verification must use the approved method and suitable test equipment where applicable. Test-before-touch and electrical verification are for authorized competent personnel; controls must be returned to a safe state after verification.",
      "Group lockout or complex multi-team work requires a clear lock ownership and handover system. No one should remove another person's personal lock except through the formally approved exceptional process.",
      "If a casualty is pinned by a load, assess whether supporting members or the machine frame could shift when the load is relieved. Use engineered stabilization and controlled release; never place hands or body parts in a potential crush path.",
      "A rescue plan should identify who can authorize isolation, who understands the machine, who leads technical release, who provides medical care, and what backup exists if the planned release fails.",
      "Do not assume a machine is safe because its motor is silent. Gravity, stored pressure, rotating inertia, spring force or an automatic restart signal can remain hazardous after shutdown.",
      "Where amputation or severe bleeding is suspected, activate EMS immediately. Preserve any separated part only according to current first-aid/medical guidance; do not delay casualty care or improvise treatment.",
      "Machine guarding and interlocks are safety-critical. Temporary bypasses, defeated sensors, missing guards or unapproved modifications must be treated as serious restart barriers.",
    ],
    siteImplementation: <String>[
      'Pre-job: identify machines with entrapment potential, emergency stops, isolation points, stored-energy hazards, rescue access, competent authorized isolators and emergency contact arrangements.',
      'Ensure machine-specific isolation diagrams and manufacturer instructions are accessible to authorized personnel; do not rely on memory or generic lockout labels alone.',
      'Train operators to stop safely, raise alarm, keep others clear and never restart or reverse a machine to free a person without direction.',
      'At the incident: activate alarm; stop work in the surrounding area; prevent access to controls; appoint incident lead; request ambulance and technical rescue; identify machine and casualty status.',
      'Authorized personnel isolate all energy sources under the approved procedure, apply personal/group locks or equivalent site controls, release or restrain stored energy safely, and verify isolation before rescue access.',
      'Technical rescue lead evaluates load, pinch points, access, movement path, required tools, casualty condition and contingency if the first release attempt fails.',
      'Keep a safe exclusion zone around suspended or potentially moving components. Use rated supports and engineered stabilization only under competent direction.',
      'First aider maintains communication, monitors responsiveness and breathing, controls bleeding within training and prepares for rapid medical handover. Avoid unnecessary manipulation of trapped parts.',
      'Document isolation points, locks, verification, rescue decisions, tools used, injuries, machine condition, witnesses and restart authorization. Preserve evidence without compromising safety.',
      'Before restart: investigate, repair, test guards/interlocks, review risk assessment and procedure, brief affected workers and obtain formal release from responsible management.',
      "Keep machine isolation instructions at or readily accessible from the equipment, with an up-to-date diagram identifying every energy-isolating device and stored-energy release point.",
      "Conduct a pre-task rescue review for unusual maintenance, jam clearing, cleaning, confined access or work where a person could be caught. Confirm rescue tools can reach the casualty without exposing rescuers.",
      "After rescue, quarantine the machine and tag it out of service. Record lock numbers/owners and do not remove controls until the formal site procedure permits it.",
      "Before restart, verify all persons are clear, tools and temporary supports are removed, guards are restored, interlocks function, affected workers are notified and the authorized owner signs release.",
    ],
    practicalExample: <String>[
      'Scenario: a worker’s sleeve and forearm are caught at a conveyor roller. The emergency stop has been pressed, but the belt remains under tension and a suspended product load is nearby.',
      'Raise the alarm and request ambulance plus the site’s authorized machine isolator/technical rescue team. Keep other workers away from controls and the suspended load.',
      'Do not pull the worker, reverse the conveyor, cut the belt, or remove the roller guard. Tell responders the machine ID, stop status, visible energy sources and casualty condition.',
      'Authorized isolator applies the machine-specific isolation process, identifies electrical and stored mechanical energy, restrains the load as approved and verifies safe condition.',
      'The rescue lead plans controlled release with medical support ready. First aider reassures the casualty and provides care within competence without applying force to the trapped limb.',
      'After release, transfer directly to medical care. Maintain equipment isolation, secure the scene and begin a formal investigation and machine-safety review.',
      'Field checklist: alarm; controls secured; competent isolation authority present; all energy sources identified; stored energy controlled; no improvised movement; medical support ready; formal restart hold.',
      "If the casualty is unconscious or cannot communicate, do not infer that a stopped machine is safe. Keep the scene controlled and wait for authorized isolation verification and the technical rescue lead.",
      "Handover example: 'Conveyor C-04; emergency stop activated; main isolator identified but not yet verified; roller tension and product load remain; casualty's arm trapped; ambulance requested; no restart authorized.'",
    ],
    stopWorkConditions: <String>[
      'Any machine or stored-energy source may restart, rotate, descend, release pressure or shift unexpectedly.',
      'Isolation points are unknown, access is unsafe, verification cannot be completed, or the authorized isolator is unavailable.',
      'A suspended load, unstable machine, damaged support or uncertain load path threatens casualty or rescuers.',
      'Rescue requires unapproved cutting, lifting, jacking, reversing, dismantling or entry into a danger zone without a competent plan.',
      'Casualty condition deteriorates, communications fail, or medical/technical support is inadequate for the proposed intervention.',
    ],
    interviewQuestions: <String>[
      'Q: Is pressing emergency stop enough for rescue? A: No. It may stop motion but does not prove all energy is isolated or stored energy controlled. Authorized personnel must follow the machine-specific energy-control process and verify safe state.',
      'Q: Who may isolate the machine? A: Personnel authorized and competent under the site energy-control/LOTO system, following the equipment-specific procedure.',
      'Q: Why must rescuers avoid reversing the machine? A: Reversal can tighten entrapment, move a load, cause further crushing, or expose rescuers to unexpected motion.',
      'Q: What is required before restart? A: Casualty removed and medically handed over, investigation and repairs completed, guards/interlocks restored and tested, affected workers briefed, and formal release by responsible authority.',
      "Q: What does LOTO achieve? A: It controls hazardous energy by identifying sources, isolating them, applying locks/tags under the site system, controlling stored energy and verifying safe state before exposure.",
      "Q: Who authorizes restart? A: The designated responsible equipment/site authority after inspection, restoration, personnel clearance, notification and completion of the formal release process.",
    ],
  ),
  EmergencyRescueTopic(
    id: 'ER-15',
    title: 'Water, Flooding & Drowning Rescue',
    purpose:
        'Water rescue covers a person overboard, fall into water, flooding, drowning or near-drowning, and incidents near tanks, pits, canals, shorelines or temporary water bodies. The safest initial response is often reach or throw from a stable position, raise the alarm, and bring trained water-rescue and medical responders. An untrained rescuer must not enter water or become a second casualty.',
    scope:
        'Applies to marine/offshore interfaces, waterfront projects, drainage channels, excavation flooding, tanks, reservoirs, temporary ponds, docks, boats and work near open water. Consider current, tide, depth, visibility, water temperature, contamination, entrapment, access, weather, electrical hazards and rescue equipment.',
    keyKnowledge: <String>[
      'Recognize distress: unexpected immersion, inability to keep the airway clear, silent struggling, loss of response, missing person near water, or a person clinging to an edge or object.',
      'Raise alarm immediately and state exact water location, access route, number of people, last-seen point, current/tide or flow, known hazards and whether the casualty is visible.',
      'Use the hierarchy of rescue: reach with a suitable tool from a secure position; throw a lifebuoy/line or flotation aid; use a rescue craft or trained water-rescue team; in-water entry only by trained, equipped responders under an approved plan.',
      'Do not jump in, swim after the casualty, form an unprotected human chain, or tie a line around a rescuer. A panicked casualty may grab and submerge a rescuer.',
      'Never enter floodwater or a tank/pit where electrical contact, contamination, hidden openings, strong flow, entrapment or unknown depth may exist without specialist assessment and controls.',
      'For man-overboard, maintain continuous visual pointing if safe, throw flotation, activate the vessel/site alarm, record last-seen location and follow the approved vessel or site recovery plan. Do not lose sight while retrieving equipment.',
      'Rescue craft and lines introduce hazards: propellers, entanglement, line recoil, unstable banks, edge collapse, poor visibility and changing current. Only trained operators should deploy them.',
      'Once recovered to a safe place, assess responsiveness and normal breathing. If unresponsive and not breathing normally, activate emergency medical response and begin CPR/AED according to current training and dispatcher instructions.',
      'Provide rescue breaths and CPR in accordance with current first-aid certification and emergency-dispatch guidance; drowning is an oxygen-related emergency. Do not delay resuscitation for attempts to drain water from the lungs.',
      'Do not use abdominal thrusts or hang the casualty upside down to remove water. These actions delay effective ventilation and may cause harm.',
      'Remove wet clothing and prevent further heat loss when safe; monitor breathing and consciousness. All significant submersion or suspected drowning requires urgent medical assessment, even if the person appears to recover.',
      'Contaminated water may expose rescuers and casualty to sewage, chemicals, biological hazards or sharp debris. Use appropriate PPE and arrange decontamination/medical advice as directed.',
      'After recovery, secure the water edge, account for all personnel, preserve last-seen information, inspect barriers and access controls, and do not resume work until the responsible authority releases the area.',
      "Differentiate still water, flowing water, tidal water and confined water spaces. Flow can pin a person against an obstruction; a bank can collapse; visibility can hide cables, debris, holes or entrapment points.",
      "A throw line must be deployed by a trained person from a stable position, with attention to line entanglement, recoil, snagging and a safe retrieval direction. Do not wrap the line around a rescuer or secure it to an unverified anchor.",
      "A person who has disappeared beneath water should be reported with the last-seen point and time, not a guessed location. Preserve witness observations and direct trained responders to the area; do not conduct an unplanned search entry.",
      "For a recovered casualty, check responsiveness and normal breathing. If not breathing normally, start CPR/AED as trained and follow current dispatcher instructions; if breathing, maintain airway, monitor continuously and arrange urgent medical assessment.",
      "Do not delay CPR to remove wet clothing, search for water in the lungs, or perform abdominal thrusts to expel water. Prioritize effective resuscitation and protection from further exposure.",
      "Consider secondary hazards during recovery: contaminated water, hypothermia, electrical services, unstable edge, boat propellers, ropes, sharp debris and bystanders crowding the landing point.",
      "A water rescue team needs a backup plan, communications, suitable PPE/flotation, defined entry/exit points and a safe recovery location. A boat launch or edge approach must not block ambulance access.",
      "Near-drowning can lead to delayed respiratory complications. Even a casualty who becomes alert after recovery needs medical evaluation and monitoring according to medical direction.",
    ],
    siteImplementation: <String>[
      'Before work: identify open water, tanks, pits, channels, flood pathways and edge hazards; provide suitable barriers, lighting, warning signs, access controls and approved rescue equipment based on risk assessment.',
      'Confirm who raises the alarm, who calls external emergency services, who deploys flotation aids, who controls the edge, and how responders access the exact location.',
      'Inspect and maintain life rings, throw lines, rescue poles, ladders, boats, radios and personal flotation equipment according to manufacturer and site procedures; keep equipment accessible and unobstructed.',
      'Brief workers on no-entry rescue, alarm words, last-seen-point reporting, safe throw/reach technique within training, and restrictions on entering water or flood zones.',
      'At incident: raise alarm; maintain visual contact and point to the casualty if safe; throw flotation/line from stable ground; call trained water-rescue and medical support; prevent others entering.',
      'Trained team conducts recovery under incident command, considering current, bank stability, access, entanglement, contamination and backup rescue arrangements.',
      'After recovery: move to safe area, assess responsiveness and breathing, initiate CPR/AED as trained and directed, protect from temperature exposure, and arrange urgent medical evaluation.',
      'Preserve the scene and record timeline, last-seen location, water conditions, equipment used, witness details and actions. Reassess barriers, access and work method before restart.',
      "Mark the exact water body and access point on the site emergency map; include nearest gate, safe approach, rescue-equipment location and an alternate route if flooding blocks the primary route.",
      "Inspect edge barriers and rescue equipment before the task and after any event. Remove damaged equipment from service and record inspection/maintenance under site procedure.",
      "Use a buddy and communications system for work near water. Confirm weather, current/tide information where relevant, lighting, safe footing and stop-work triggers before starting.",
      "After a rescue or near miss, review why the person reached the edge, whether barriers/access controls were adequate, whether rescue equipment was reachable, and whether the task method should change.",
    ],
    practicalExample: <String>[
      'Scenario: a worker slips into a drainage channel after heavy rain. The water is moving and the bank is muddy; coworkers can see the worker but cannot reach safely.',
      'Raise alarm and give the exact channel marker, access gate, number of people and flow condition. Ask a coworker to guide responders from a safe route.',
      'From stable ground, throw an approved flotation aid/line if it can be done without approaching an unstable edge. Do not enter the water or climb down the bank.',
      'Keep visual contact and report the casualty’s position and movement. Prevent other workers from entering the channel; isolate nearby plant and electrical hazards where safe.',
      'Trained responders perform recovery. Once on safe ground, check responsiveness and normal breathing; begin CPR/AED if indicated and trained, while emergency medical services are en route.',
      'Arrange urgent medical assessment, document the event and keep the channel closed until bank stability, barriers and weather/flood conditions are reviewed.',
      'Field checklist: alarm and location; visual contact; reach/throw attempted only from safe ground; no untrained water entry; trained rescue/EMS requested; CPR/AED readiness; urgent medical handover; area release.',
      "A worker reports a colleague fell into a canal but cannot see them now. Record the last-seen point/time, raise alarm, keep observers in safe positions to point out the area, and pass that information to trained responders. Do not send coworkers into the canal.",
      "The first aider should be ready at the safe recovery point with suitable PPE and an AED, while keeping a clear route for ambulance access.",
    ],
    stopWorkConditions: <String>[
      'Rescue would require an untrained person to enter water, floodwater, a tank, pit or unstable bank.',
      'Current, tide, depth, contamination, electrical exposure or entrapment hazards are unknown or beyond responder capability.',
      'Rescue equipment is missing, damaged, inaccessible or unsuitable, or communication with the rescue team is lost.',
      'Weather, lightning, poor visibility, unstable edge or moving plant creates an uncontrolled risk to rescuers.',
      'The casualty is recovered but breathing, consciousness or temperature status is deteriorating; prioritize emergency medical care and trained intervention.',
    ],
    interviewQuestions: <String>[
      'Q: What is the first rule of water rescue? A: Do not become a second casualty. Raise alarm, maintain visual contact and use reach/throw methods from a stable position when safe; in-water rescue is for trained, equipped responders.',
      'Q: What should be reported for a person overboard? A: Exact location, last-seen point and time, casualty count, water/current conditions, visibility, access route and hazards.',
      'Q: Should water be drained from the casualty’s lungs? A: No. Do not delay effective CPR/ventilation by hanging the person upside down or using abdominal thrusts to expel water.',
      'Q: Does a recovered person need medical assessment if they feel normal? A: Yes, suspected drowning or significant submersion requires urgent medical evaluation because complications can develop after apparent recovery.',
      "Q: Why is a human chain unsafe? A: People can lose footing and be pulled into the water; use approved reach/throw equipment from stable ground and trained rescue methods.",
      "Q: What is the correct first-aid priority after recovery? A: Assess responsiveness and normal breathing, call EMS, provide CPR/AED if indicated and trained, protect from exposure, and arrange urgent medical assessment.",
    ],
  ),
  EmergencyRescueTopic(
    id: 'ER-16',
    title: 'Heat Illness & Environmental Exposure Emergency',
    purpose:
        'Heat illness and environmental exposure response protects workers affected by heat strain, heat exhaustion, suspected heat stroke, dehydration, severe sun exposure, cold stress where relevant, or sudden weather-related deterioration. The response is to stop exposure, summon medical help early for serious symptoms, begin safe cooling or protection within training, and prevent recurrence. Suspected heat stroke is a life-threatening medical emergency.',
    scope:
        'Applies to outdoor construction, roadworks, logistics, utilities, industrial work, confined or poorly ventilated hot areas, vehicle cabins, remote work fronts and other tasks with heat or environmental exposure. Follow current UAE and Emirate requirements, employer heat-stress program, occupational-health advice, weather alerts and site-specific controls; legal dates, thresholds and work-rest rules must be verified from current official sources.',
    keyKnowledge: <String>[
      'Heat-related illness can progress from heat cramps or heat exhaustion to heat stroke. Warning signs may include unusual weakness, headache, dizziness, nausea, heavy sweating, cramps, confusion, collapse, seizure or altered consciousness.',
      'Suspected heat stroke may present with confusion, collapse, seizure or altered mental status in a hot environment. Do not wait for a temperature reading or assume sweating rules it out; call emergency medical services immediately.',
      'Stop work and move the affected person to a cooler, shaded or air-conditioned safe area if this can be done without delay or danger. Remove unnecessary outer clothing and start active cooling according to first-aid training and medical-dispatch guidance.',
      'For suspected heat stroke, rapid cooling is critical. Use available safe cooling methods appropriate to the setting and responder training; protect airway and continuously monitor breathing and responsiveness. Do not give oral fluids to a confused, unconscious, vomiting or poorly responsive person.',
      'For a fully alert person with mild heat symptoms who can swallow safely, provide cool drinking water or an appropriate oral rehydration drink in small amounts, rest and medical review as indicated by site protocol. Do not force fluids.',
      'Never send a symptomatic worker back to work simply because they feel temporarily better. Return-to-work decisions require medical/occupational-health guidance and review of contributing controls.',
      'Risk increases with high heat/humidity, radiant heat, heavy physical work, impermeable PPE, poor acclimatization, inadequate recovery, dehydration, illness and certain medications. Do not make assumptions about an individual’s fitness.',
      'Use a heat-stress risk assessment that considers environmental conditions, workload, clothing/PPE, acclimatization, work duration, shade/cooling, hydration access, supervision and emergency access. Use approved measurement methods and current official/site criteria.',
      'Acclimatization must be planned for new, returning or transferred workers and adjusted for actual task and conditions. Supervisors must monitor workers rather than relying only on self-report.',
      'Provide potable water, accessible shaded/cool recovery areas, work-rest arrangements, buddy observation, supervisor checks, suitable PPE and clear symptom reporting. Controls must match current regulatory and site requirements.',
      'Workers should report symptoms early without fear of penalty. Supervisors should stop or modify work when conditions exceed approved limits or workers show signs of heat strain.',
      'Consider other environmental emergencies: dust storm, lightning, heavy rain, flooding, poor visibility and cold exposure where applicable. Follow official alerts and site shelter/stop-work triggers.',
      'Record symptoms, environmental conditions, task, PPE, work/rest pattern, hydration availability, response timeline and medical referral while respecting privacy. Investigate control failures and adjust the work plan.',
      "Heat stress is influenced by environmental heat and humidity, radiant heat, metabolic workload, clothing/PPE, acclimatization, hydration, rest and individual factors. A single air-temperature reading does not describe the full risk.",
      "Heat exhaustion may include heavy sweating, weakness, headache, dizziness, nausea and cramps. Confusion, collapse, seizure or altered mental status in heat should be treated as suspected heat stroke and escalated immediately.",
      "Do not rely on skin being dry or wet to decide whether heat stroke is present. Do not delay EMS while searching for a thermometer or waiting for symptoms to resolve.",
      "Cooling methods must fit the casualty, site resources and responder training. Protect privacy and dignity, avoid unsafe movement, monitor airway/breathing, and follow emergency-dispatch/medical guidance.",
      "Hydration is a preventive control, not a substitute for work-rest, shade, acclimatization, workload adjustment or medical response. Avoid forcing large volumes of water or giving oral fluids to a person with altered consciousness.",
      "Supervisors should watch for behavioral change, slowed responses, unusual errors, staggering or withdrawal as well as workers' self-reported symptoms. Buddy checks are especially important for isolated or strenuous tasks.",
      "Review heat exposure after a change in task, PPE, work location, weather, shift pattern or workforce acclimatization. Reassess controls when conditions change rather than relying on yesterday's plan.",
      "Environmental emergencies may require shelter or evacuation: lightning, dust storm, heavy rain, flash flooding and poor visibility. Use current official alerts and the site's approved trigger/action matrix.",
      "Medical clearance and a controlled return-to-work process are important after significant heat illness. Protect medical privacy and do not let production pressure override health advice.",
    ],
    siteImplementation: <String>[
      'Before shift: review current official weather alerts and site heat-stress controls; identify high-exposure tasks, remote work fronts, emergency access and cooling locations.',
      'Confirm current legal requirements and company procedures for heat-stress management, work timing, breaks, monitoring, training and records; do not rely on an outdated calendar or copied threshold.',
      'Provide potable water, shaded/air-conditioned recovery, suitable PPE, communication, first-aid coverage and a clear method to summon ambulance/medical support.',
      'Plan acclimatization for new or returning workers, workload progression and additional supervision based on occupational-health advice and site policy.',
      'Brief crews on early symptoms, buddy checks, stop-work authority, reporting without delay, safe cooling, and prohibition on leaving a severely symptomatic person alone.',
      'At incident: stop exposure; call medical support for serious symptoms or suspected heat stroke; move to a cooler safe place; begin cooling and monitor airway/breathing/responsiveness within training.',
      'Do not give oral fluids to an unconscious, confused, vomiting or poorly responsive casualty. Do not delay emergency services while attempting self-treatment.',
      'Arrange medical assessment and supervised transport as indicated. Record the timeline and conditions; preserve dignity and confidentiality.',
      'Before restarting: review weather and task conditions, work/rest and hydration controls, staffing, acclimatization, cooling access and supervisor monitoring; obtain authorization under site procedure.',
      'For dust storm, lightning, flood or severe weather, follow current official warnings and site shelter/evacuation triggers; stop exposed work and account for personnel.',
      "At toolbox talk, identify symptoms, who to notify, how to summon help, nearest cooling/first-aid point, and who can stop work. Ensure workers understand reporting is expected, not a disciplinary failure.",
      "Use current official UAE/Emirate requirements and the employer's current heat-stress procedure for dates, restrictions, measurement methods and mandatory records. Verify changes before each season; do not copy old circulars as current law.",
      "For remote work fronts, confirm communication coverage, vehicle access, cooling capability, buddy assignment and a clear casualty evacuation route before work begins.",
      "After a heat illness event, review environmental data, task intensity, PPE, acclimatization, water/cooling access, supervision, response time and medical advice; update the risk assessment and briefing.",
    ],
    practicalExample: <String>[
      'Scenario: during outdoor work, a worker becomes confused, unsteady and collapses. The work area is hot and exposed; coworkers suggest giving water and letting the worker rest.',
      'Treat as suspected heat stroke: stop work, call emergency medical services/site emergency response immediately, give exact location and access route, and assign someone to meet responders.',
      'Move the worker to a cooler safe location if this can be done promptly and safely. Remove unnecessary outer layers and begin active cooling according to trained first-aid/dispatcher guidance.',
      'Check responsiveness and breathing continuously. If the person is not breathing normally, follow current CPR/AED training and dispatcher instructions. Do not give water or food to a confused or poorly responsive casualty.',
      'Continue cooling and monitoring until medical responders take over. Provide the symptom timeline, task, PPE, conditions and actions taken.',
      'Suspend similar exposed work, check other workers, review current weather and controls, and restart only after the responsible supervisor/HSE/occupational-health process confirms adequate protection.',
      'Field checklist: exposure stopped; EMS called for serious symptoms; cool safe location; active cooling within training; airway/breathing monitored; no oral fluids if altered; medical handover; crew reassessment; controls reviewed.',
      "If a worker reports dizziness but is fully alert and breathing normally, stop exposure, move to a cooler place, assess and follow site first-aid/medical procedure. Escalate promptly if symptoms persist, worsen or any red-flag symptom appears.",
      "If a worker collapses or becomes confused, treat as suspected heat stroke: call EMS immediately, begin safe active cooling, monitor airway/breathing and do not give oral fluids.",
    ],
    stopWorkConditions: <String>[
      'A worker shows confusion, collapse, seizure, altered consciousness, severe weakness or other signs of potentially serious heat illness.',
      'Current official/site heat-stress criteria or weather alerts require work modification, suspension, shelter or evacuation.',
      'Cooling, potable water, shade/recovery, communications or emergency medical access are unavailable for the planned exposure.',
      'A worker is symptomatic, has not recovered under medical guidance, or is being pressured to return before clearance.',
      'Lightning, dust storm, flooding, poor visibility or other environmental conditions create an uncontrolled exposure or evacuation risk.',
    ],
    interviewQuestions: <String>[
      'Q: What is the key difference in response to suspected heat stroke? A: Treat it as life-threatening: summon emergency medical help immediately, stop exposure, start safe active cooling and monitor airway/breathing. Do not wait for a temperature reading.',
      'Q: Can water be given to a confused casualty? A: No. Do not give oral fluids to a confused, unconscious, vomiting or poorly responsive person because of aspiration risk.',
      'Q: What controls should a supervisor verify before hot work? A: Current requirements and weather, task/workload risk assessment, acclimatization, water, shade/cooling, work-rest plan, suitable PPE, buddy/supervisor monitoring and emergency access.',
      'Q: When may the worker return? A: Only after appropriate medical/occupational-health guidance and site authorization, with contributing exposure controls reviewed; temporary symptom improvement alone is not clearance.',
      "Q: Can a supervisor use only the weather app temperature to decide whether work is safe? A: No. Use the approved site risk assessment and required measurement method, considering humidity, radiant heat, workload, PPE, acclimatization and current official requirements.",
      "Q: What should happen after a worker recovers from heat symptoms? A: Medical/occupational-health advice and site return-to-work authorization should guide recovery; review and correct exposure controls before resuming similar work.",
    ],
  ),
];
