import 'package:flutter/material.dart';

class HandbookTopic { final String title, overview, field, records; const HandbookTopic({required this.title, required this.overview, required this.field, required this.records}); }
const occupationalHealthPart1 = <HandbookTopic>[
"+"
".join(rows)+"
];

class OccupationalHealthHandbookPage extends StatelessWidget { const OccupationalHealthHandbookPage({super.key}); @override Widget build(BuildContext context) => Scaffold(backgroundColor: const Color(0xFFF6F8F7), appBar: AppBar(title: const Text('Occupational Health Handbook'), backgroundColor: const Color(0xFF0B5D4B), foregroundColor: Colors.white), body: ListView.builder(padding: const EdgeInsets.all(12), itemCount: occupationalHealthPart1.length, itemBuilder: (context, i) { final t=occupationalHealthPart1[i]; return Card(color: Colors.white, child: ListTile(leading: const CircleAvatar(backgroundColor: Color(0xFFE5F4E9), child: Icon(Icons.health_and_safety, color: Color(0xFF159447))), title: Text(t.title, style: const TextStyle(fontWeight: FontWeight.w600)), subtitle: const Text('Professional field handbook'), trailing: const Icon(Icons.chevron_right), onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => _TopicDetail(topic:t))))); })); } }
class _TopicDetail extends StatelessWidget { final HandbookTopic topic; const _TopicDetail({required this.topic}); Widget section(String h,String b)=>Padding(padding: const EdgeInsets.only(bottom:18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children:[Text(h,style:const TextStyle(fontSize:17,fontWeight:FontWeight.bold,color:Color(0xFF0B5D4B))),const SizedBox(height:7),SelectableText(b,style:const TextStyle(fontSize:15,height:1.5))])); @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF6F8F7),appBar:AppBar(title:Text(topic.title),backgroundColor:const Color(0xFF0B5D4B),foregroundColor:Colors.white),body:ListView(padding:const EdgeInsets.all(18),children:[section('Technical overview & applicability',topic.overview),section('Site implementation & risk controls',topic.field),section('Applicable office documents & records',topic.records),section('UAE compliance note','Confirm the latest applicable UAE federal, emirate, regulator, client and sector requirements for the project. Exposure limits and medical decisions must be confirmed by competent occupational hygiene and medical professionals.') ]));}
