/// Phase 1 content: Environmental Management Plan (EMP).
/// Project-specific legal and permit applicability must be verified before issue.
class EnvironmentalEmpTemplate {
  EnvironmentalEmpTemplate._();

  static const String title = 'Environmental Management Plan (EMP)';
  static const String purpose = 'A controlled project plan that translates the project scope, environmental aspects and applicable obligations into assigned prevention, mitigation, monitoring, response and reporting controls. It is not itself an environmental permit or authority approval.';

  static const List<Map<String, String>> sections = [
    {'heading': 'Document control', 'body': 'Project: [enter] | Contract/package: [enter] | Site/emirate: [enter] | Document No.: [enter] | Revision: [enter] | Status: Draft / For Review / Approved for Use | Prepared by/name/date: [enter] | Reviewed by/name/date: [enter] | Approved by/name/date: [enter] | Supersedes: [enter]. Maintain revision history and controlled distribution.'},
    {'heading': '1. Purpose and objectives', 'body': 'State the project-specific environmental outcomes: prevent pollution; avoid or minimize adverse effects; comply with verified applicable obligations and approval conditions; assign resources and responsibilities; monitor performance; respond to incidents; and retain auditable evidence. Set measurable objectives only where baseline, method, owner, target and due date are defined.'},
    {'heading': '2. Project description and scope', 'body': 'Describe location, boundaries, phases, work packages, workforce, operating hours, plant, temporary facilities, utilities, access and interfaces. Identify included subcontractors and activities. Attach a current site layout showing boundaries, drains, water bodies, sensitive receptors, storage, waste areas, fuel/chemical areas, monitoring points and emergency access. Mark unknowns for pre-start verification.'},
    {'heading': '3. Environmental context and receptors', 'body': 'Record verified baseline conditions and nearby receptors: air, surface water, groundwater, soil, noise-sensitive locations, ecology, cultural/heritage constraints and community interfaces as relevant. Identify data source, date, survey method, limitations and person validating it. Do not present assumptions as surveyed facts.'},
    {'heading': '4. Applicability and regulatory obligations', 'body': 'Create an obligation register for each project requirement. Classify separately: (A) UAE federal law/regulation; (B) relevant emirate authority requirement; (C) permit/EIA/approval/NOC condition; (D) client/contract specification; (E) company procedure; (F) recommended practice. For each, record exact instrument/title, article/clause/condition, issuing authority, official source URL or controlled copy, effective/review date, activity/location applicability, owner, evidence and compliance status. Abu Dhabi and Dubai requirements must not be assumed interchangeable. Confirm which authority and approval route applies to this specific site and activity with the project permitting lead/authority.'},
    {'heading': '5. Environmental aspects and impact assessment', 'body': 'For each activity, identify input/output and aspect (e.g., dust generation, noise, discharge, waste, fuel storage, lighting, land disturbance); identify receptor and potential impact; record normal, abnormal and emergency conditions; existing controls; consequence/likelihood or approved significance method; residual rating; additional action, owner and due date. State the project-approved scoring method and acceptance criteria; do not invent universal scores.'},
    {'heading': '6. Roles and responsibilities', 'body': 'Project Manager: resources and implementation accountability. Environmental Manager/Officer: maintain EMP, obligation register, monitoring, advice, reporting and escalation. Construction/Operations Manager: integrate controls into method statements and sequencing. Supervisors: pre-task briefings and field checks. Procurement: verify approved providers where required. Contractors: implement and provide records. Document Controller: revision/distribution. Emergency Lead: response coordination. Adapt titles to the approved project organization chart.'},
    {'heading': '7. Operational controls', 'body': 'For each significant aspect, provide a linked control sheet or method statement covering activity/location, responsible supervisor, pre-start checks, equipment and containment, work sequence, exclusion/protection zones where relevant, inspection trigger/frequency, acceptance criteria from verified source, records, abnormal-condition response and stop-work/escalation triggers. Address dust, noise/vibration, wastewater, stormwater, soil, chemicals/fuels, waste, concrete washout, ecology and nuisance only where relevant to scope.'},
    {'heading': '8. Waste management', 'body': 'List anticipated waste streams and source activities; confirm classification using applicable project/authority method; define segregation, compatible containers, labels, covered/secure storage, secondary containment where needed, inspection, collection trigger, approved carrier/receiving route where required, transfer documentation, quantity reconciliation and evidence of recovery/treatment/disposal. Do not dispatch until provider, destination and required approvals are verified.'},
    {'heading': '9. Monitoring and measurement', 'body': 'For each parameter define objective, receptor/location map, method, equipment, competence, calibration/quality controls, frequency or event trigger, applicable criterion and its source, data owner, review, reporting route and response to trigger/exceedance. Monitoring frequency and numerical limits are project/permit-specific; enter only verified values. Preserve raw data, field sheets, chain-of-custody and laboratory reports as applicable.'},
    {'heading': '10. Training, communication and consultation', 'body': 'Identify audiences, language/accessibility needs, induction topics, task-specific briefings, specialist competence, schedule, trainer, attendance and understanding checks. Communicate environmental constraints and emergency contacts to subcontractors and visitors. Record complaints/concerns, acknowledgement, investigation, response and close-out.'},
    {'heading': '11. Emergency preparedness and response', 'body': 'Link to the approved site emergency plan. Include credible environmental scenarios (spill, uncontrolled discharge, firewater runoff, release, extreme weather or other site-specific event), alarm/notification, source isolation, protection of drains/receptors, trained responders, compatible spill materials, waste handling after response, authority/client notifications where applicable, recovery, investigation and drill learning. Confirm contact numbers and notification deadlines from current project instructions and applicable conditions.'},
    {'heading': '12. Inspection, audit and corrective action', 'body': 'Set risk-based inspection and audit schedule with owner, scope, checklist, evidence, finding classification, action owner/due date, escalation for overdue/high-risk items, closure evidence and effectiveness verification. Repeated or significant findings trigger review of risk assessment, method, competence and resources.'},
    {'heading': '13. Reporting and record keeping', 'body': 'Define daily/weekly/monthly reporting cadence as required by project/contract/approval; data owner and cut-off; KPI definitions; validation and reconciliation; recipient and submission route; incident/complaint escalation; record repository, access, backup, retention source and archive owner. Do not assign a universal retention period: record the actual legal, permit, contract or approved company schedule basis.'},
    {'heading': '14. Change management and review', 'body': 'Review before material change to scope, design, method, location, receptor, contractor, plant, permit condition, law, incident trend or monitoring result. Record change description, aspect/risk review, approvals, affected documents, briefing and effective date. Review at the project-defined interval and before relevant phase transitions.'},
    {'heading': '15. Appendices and forms', 'body': 'A. Site environmental constraints/receptor plan. B. Applicable obligations and permit-condition register. C. Aspect-impact register and scoring method. D. Aspect-specific control/method statement index. E. Monitoring schedule and location map. F. Waste stream and approved route register. G. Inspection checklist. H. Training matrix. I. Emergency contacts and spill response card. J. Incident/complaint form. K. Corrective-action tracker. L. Monthly environmental report template. M. Revision and distribution register. Include only applicable appendices and mark N/A with reason.'},
  ];

  static const List<Map<String, String>> applicabilityMatrix = [
    {'jurisdiction': 'UAE Federal', 'verify': 'Identify the current federal environmental instruments relevant to the activity, location, waste/emissions/discharge and any federal permit or reporting trigger. Record exact title, clause, official source and applicability; do not infer from a generic checklist.'},
    {'jurisdiction': 'Abu Dhabi', 'verify': 'If the project is in Abu Dhabi, confirm current emirate authority requirements, project classification, environmental permit/EIA or approval conditions, waste and monitoring obligations, and any sector/site-specific conditions with the authorized project permitting route.'},
    {'jurisdiction': 'Dubai', 'verify': 'If the project is in Dubai, confirm current Dubai authority and municipality/sector requirements, project classification, approval route, permit conditions and reporting obligations. Do not copy Abu Dhabi-specific requirements as if automatically applicable.'},
    {'jurisdiction': 'Other emirate / free zone / client', 'verify': 'Identify the competent local authority, free-zone rules if applicable, landowner/client requirements and contract specifications. Record precedence and resolve conflicts through authorized compliance review.'},
  ];

  static const List<String> preIssueChecks = [
    'Project/site/emirate and activity scope verified',
    'Official legal and permit sources recorded with clause/condition',
    'Applicability marked: legal / permit / client-contract / company / recommended',
    'Aspect-impact assessment linked to current work packages',
    'Owners, resources, monitoring and response arrangements assigned',
    'Numerical limits and frequencies supported by a cited applicable source',
    'Appendices/forms populated or marked N/A with reason',
    'Review/approval completed and controlled revision issued',
    'Affected supervisors and contractors briefed; records retained',
  ];
}
