// lib/data/abu_dhabi/abu_dhabi_cop_54_waste_management.dart
//
// SafeNexus HSE — Abu Dhabi HSE Reference
// CoP 54.0 — Waste Management
//
// Standalone Flutter page. No third-party packages required.
// To open: Navigator.push(context, MaterialPageRoute(
//   builder: (_) => const AbuDhabiCop54Page(),
// ));
//
// Regulatory note:
// Verify the current official ADPHC CoP 54.0 document and applicable
// authority/facility requirements before treating any operational value
// as a legal limit. This page separates practical guidance from
// jurisdiction-specific requirements.

import 'package:flutter/material.dart';

class AbuDhabiCop54Page extends StatelessWidget {
  const AbuDhabiCop54Page({super.key});

  static const Color _deepGreen = Color(0xFF126B3A);
  static const Color _green = Color(0xFF168044);
  static const Color _lime = Color(0xFF5B9F0B);
  static const Color _amber = Color(0xFFC58A00);
  static const Color _orange = Color(0xFFB6530A);
  static const Color _red = Color(0xFF9E1B1B);
  static const Color _ink = Color(0xFF17231C);
  static const Color _muted = Color(0xFF65736A);
  static const Color _surface = Color(0xFFF4F7F5);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: _surface,
      appBar: AppBar(
        title: const Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Abu Dhabi HSE Reference',
                style: TextStyle(fontSize: 17, fontWeight: FontWeight.w800)),
            Text('CoP 54.0 • Waste Management',
                style: TextStyle(fontSize: 12, fontWeight: FontWeight.w500)),
          ],
        ),
        backgroundColor: _deepGreen,
        foregroundColor: Colors.white,
        elevation: 0,
      ),
      body: SafeArea(
        child: ListView(
          padding: const EdgeInsets.fromLTRB(16, 16, 16, 30),
          children: [
            _hero(),
            const SizedBox(height: 18),
            _sectionTitle('WASTE MANAGEMENT HIERARCHY'),
            const SizedBox(height: 10),
            _hierarchyCard(
              number: '1',
              title: 'PREVENT',
              example:
                  'Plan material quantities correctly; avoid unnecessary packaging and over-ordering.',
              color: _deepGreen,
              icon: Icons.shield_outlined,
            ),
            _hierarchyCard(
              number: '2',
              title: 'REDUCE',
              example:
                  'Use reusable delivery crates and optimize cutting plans to reduce off-cuts.',
              color: _green,
              icon: Icons.trending_down,
            ),
            _hierarchyCard(
              number: '3',
              title: 'REUSE',
              example:
                  'Reuse serviceable formwork timber and pallets after inspection and approval.',
              color: _lime,
              icon: Icons.replay,
            ),
            _hierarchyCard(
              number: '4',
              title: 'RECYCLE',
              example:
                  'Segregate clean metal, cardboard, suitable plastics and concrete for approved recycling routes.',
              color: _amber,
              icon: Icons.autorenew,
            ),
            _hierarchyCard(
              number: '5',
              title: 'RECOVER',
              example:
                  'Send eligible residual streams to an authorized recovery facility where accepted.',
              color: _orange,
              icon: Icons.energy_savings_leaf_outlined,
            ),
            _hierarchyCard(
              number: '6',
              title: 'DISPOSE',
              example:
                  'Use an approved receiving facility and retain required transfer and consignment records.',
              color: _red,
              icon: Icons.delete_outline,
            ),
            const SizedBox(height: 20),
            _sectionTitle('CoP 54.0 FIELD HANDBOOK'),
            _infoCard(
              '1. Purpose and objectives',
              'Waste management covers identification, classification, segregation, collection, storage, movement, recovery and final disposal of waste generated by work activities.',
              [
                'Protect workers, visitors and the public.',
                'Prevent soil, water and air pollution.',
                'Reduce waste generation and promote reuse/recycling.',
                'Maintain traceability from the point of generation to the approved destination.',
                'Prevent uncontrolled dumping, burning, leakage and mixing of incompatible wastes.',
              ],
            ),
            _infoCard(
              '2. Scope and applicability',
              'Apply the relevant waste controls to project, workplace, camp, workshop and operational waste streams. Confirm additional rules for special waste streams and the competent authority.',
              [
                'Construction: concrete, timber, metal, packaging and domestic waste.',
                'Oil & Gas: used oil, filters, oily absorbents and process-related waste.',
                'Offshore: segregated waste, safe temporary storage and controlled transfer ashore.',
                'Workshop: used filters, batteries, contaminated containers and scrap.',
                'Healthcare or specialist waste: follow the applicable dedicated requirements; do not treat it as ordinary general waste.',
              ],
            ),
            _infoCard(
              '3. Waste classification',
              'Classify waste using its source, composition, properties and applicable authority criteria. Do not decide hazardous status by colour or appearance alone.',
              [
                'Non-hazardous examples: clean cardboard, paper, clean packaging, scrap metal and suitable concrete rubble.',
                'Potentially hazardous examples: used oil, solvent residues, chemical-contaminated absorbents, certain batteries and chemical sludge.',
                'Medical, radioactive and other specialist streams require their own applicable controls.',
                'If identity is unknown: do not open, mix or handle casually; isolate safely and seek competent identification.',
              ],
            ),
            _infoCard(
              '4. Employer / main contractor responsibilities',
              'Establish and implement a suitable waste management system for the workplace and its contractors.',
              [
                'Prepare and communicate the Waste Management Plan and risk assessments.',
                'Identify waste streams and define approved segregation routes.',
                'Provide suitable, sufficient and maintained containers and storage areas.',
                'Select appropriately licensed/permitted service providers and receiving facilities.',
                'Arrange training, emergency arrangements, inspections and record retention.',
                'Review performance, incidents, non-conformances and corrective actions.',
              ],
            ),
            _infoCard(
              '5. HSE Officer and supervisor duties',
              'HSE personnel verify implementation; line supervisors control day-to-day work and workers follow the site arrangements.',
              [
                'Inspect bins, skips, labels, storage conditions, access and housekeeping.',
                'Check provider permits, destination acceptance and transfer documentation.',
                'Stop unsafe mixing, uncontrolled discharge or unauthorized disposal.',
                'Record findings, assign owners and follow corrective actions to closure.',
                'Brief workers on waste hazards, PPE, spill response and reporting.',
              ],
            ),
            _infoCard(
              '6. Segregation and collection',
              'Keep waste streams separate at the point of generation and use designated, compatible containers.',
              [
                'Label containers with clear waste description and hazard information as applicable.',
                'Do not place oily rags, chemicals, batteries or unknown waste in general skips.',
                'Keep lids closed where needed; prevent overfilling, windblown litter and access by unauthorized persons.',
                'Use safe manual-handling methods and suitable tools for sharp or heavy waste.',
                'Keep collection routes clear and protect pedestrians from moving plant and waste vehicles.',
              ],
            ),
            _infoCard(
              '7. Hazardous waste storage',
              'Storage must be suitable for the waste properties, container, quantity, site conditions and applicable authority requirements.',
              [
                'Check compatibility; segregate incompatible substances.',
                'Use sound, suitable containers; inspect for corrosion, damage and leakage.',
                'Provide containment where required by the risk assessment and applicable rules.',
                'Protect from weather, heat, ignition sources and unauthorized access as appropriate.',
                'Display required identification and emergency information.',
                'Keep suitable spill response materials available and ensure responders are trained.',
                'Do not invent a universal storage distance or bund capacity; verify the applicable approved design criteria.',
              ],
            ),
            _infoCard(
              '8. Transportation, transfer and records',
              'Use an appropriately licensed/permitted waste service provider and a receiving facility authorized for the waste stream. Verify current local requirements before dispatch.',
              [
                'Confirm waste description, classification and quantity.',
                'Check provider and destination approvals/permits.',
                'Use the applicable waste manifest, consignment or transfer note.',
                'Check load security and prevent leakage, loss or mixing during transport.',
                'Retain required records and evidence of final receipt/acceptance.',
                'CoP 54.0 identifies a minimum five-year retention period for the specified hazardous-waste consignment and Waste Transfer Note records held by the RSP; confirm the current official clause and any stricter project/legal rule.',
              ],
            ),
            _infoCard(
              '9. Risk assessment — common hazards',
              'Assess each waste stream and task before work begins, including collection, handling, storage, loading and spill response.',
              [
                'Sharp edges / protruding nails → cuts, punctures and infection risk.',
                'Oily or wet waste → slips, falls and possible fire escalation.',
                'Chemical residues → skin/eye injury, inhalation exposure or reaction.',
                'Heavy or awkward waste → strains, crush injuries and dropped objects.',
                'Unstable or overfilled skips → falling materials and struck-by injuries.',
                'Poor segregation or uncontrolled disposal → environmental contamination and regulatory non-compliance.',
              ],
            ),
            _infoCard(
              '10. Hierarchy of controls — site application',
              'Apply the hierarchy of controls to waste hazards; PPE is the last line of defence, not a substitute for safe systems.',
              [
                'Eliminate: avoid unnecessary hazardous materials or excess packaging where practicable.',
                'Substitute: choose less hazardous materials/processes where technically suitable.',
                'Engineering: closed containers, suitable containment, mechanical handling and guarded collection points.',
                'Administrative: waste plan, segregation labels, training, inspection, permits and approved collection schedules.',
                'PPE: task-specific gloves, safety footwear, eye/face protection and other PPE identified by assessment.',
              ],
            ),
            _scenario(
              title: '11. Practical example A — mixed construction skip',
              situation:
                  'Concrete rubble, timber, metal off-cuts, plastic packaging and oily absorbents are found in one skip.',
              actions: [
                'Stop further disposal into the mixed skip and assess immediate hazards.',
                'Arrange competent segregation; do not ask untrained workers to hand-sort unknown or contaminated waste.',
                'Set up clearly identified separate collection points.',
                'Move contaminated material through the approved hazardous-waste route.',
                'Brief the crew, record the finding and verify corrective action during re-inspection.',
              ],
            ),
            _scenario(
              title: '12. Practical example B — used-oil drum leak',
              situation:
                  'A used-oil drum is leaking in a workshop and oil is moving toward a drain.',
              actions: [
                'Stop work, warn people and restrict access; remove ignition sources if safe.',
                'Notify the supervisor/HSE and activate the site spill response plan.',
                'Only trained responders wearing assessed PPE should intervene.',
                'Protect the drain and contain the spill using compatible spill equipment, if safe.',
                'Recover contaminated absorbents as appropriately classified waste.',
                'Arrange approved collection, report the incident and investigate the cause.',
                'For unknown chemicals, large releases, vapour or fire risk: evacuate/isolate and call the emergency response team; do not attempt improvised cleanup.',
              ],
            ),
            _scenario(
              title: '13. Practical example C — waste truck collection',
              situation:
                  'A collection vehicle arrives but its provider approval or destination details cannot be verified.',
              actions: [
                'Hold the transfer; do not dispatch waste until checks are complete.',
                'Verify provider authorization and receiving-facility acceptance for that waste stream.',
                'Check the required transfer/consignment documentation and quantity.',
                'Inspect load security and vehicle suitability for the task.',
                'Record verification and retain transfer/receipt evidence.',
              ],
            ),
            _infoCard(
              '14. Emergency preparedness',
              'Emergency arrangements must match credible waste-related events and site response capability.',
              [
                'Spill, leakage, fire, exposure, incompatible waste reaction and vehicle incident scenarios.',
                'Alarm/notification, isolation, evacuation and access control.',
                'Drain protection and environmental notification/escalation where required.',
                'Suitable spill kits, fire equipment and first-aid arrangements.',
                'Only trained and authorized personnel conduct response tasks.',
                'Preserve incident evidence, report, investigate and implement corrective actions.',
              ],
            ),
            _infoCard(
              '15. Training and toolbox talk',
              'Provide role- and task-appropriate instruction and maintain training evidence as required.',
              [
                'Waste identification and segregation rules.',
                'Container labels, safe handling and PPE.',
                'Hazardous waste storage and prohibited mixing.',
                'Spill reporting, emergency alarms and stop-work conditions.',
                'Transfer documentation and approved disposal routes.',
                'Record employee, topic, date and trainer details in the site training system.',
              ],
            ),
            _checklist(),
            _toolboxTalk(),
            _interviewQuestions(),
            _sourceNote(),
          ],
        ),
      ),
    );
  }

  Widget _hero() => Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          gradient: const LinearGradient(
            colors: [_deepGreen, _green],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
          borderRadius: BorderRadius.circular(22),
          boxShadow: [
            BoxShadow(
              color: _deepGreen.withValues(alpha: .18),
              blurRadius: 18,
              offset: const Offset(0, 8),
            )
          ],
        ),
        child: const Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(Icons.recycling, color: Colors.white, size: 34),
                SizedBox(width: 10),
                Expanded(
                  child: Text('CoP 54.0',
                      style: TextStyle(
                          color: Colors.white,
                          fontSize: 27,
                          fontWeight: FontWeight.w900)),
                ),
                _StatusPill(),
              ],
            ),
            SizedBox(height: 7),
            Text('WASTE MANAGEMENT',
                style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontWeight: FontWeight.w800)),
            SizedBox(height: 8),
            Text('Safe and responsible control of waste generated by work activities.',
                style: TextStyle(color: Colors.white, fontSize: 15, height: 1.5)),
            SizedBox(height: 12),
            Text('ADOSH-SF • Version 4.0 • 15 July 2024',
                style: TextStyle(color: Colors.white70, fontSize: 12)),
          ],
        ),
      );

  Widget _sectionTitle(String title) => Padding(
        padding: const EdgeInsets.only(top: 4, bottom: 4),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(title,
                style: const TextStyle(
                    color: _ink, fontSize: 16, fontWeight: FontWeight.w900)),
          ],
        ),
      );

  Widget _hierarchyCard({
    required String number,
    required String title,
    required String example,
    required Color color,
    required IconData icon,
  }) =>
      Container(
        margin: const EdgeInsets.only(bottom: 10),
        decoration: BoxDecoration(
          color: color,
          borderRadius: BorderRadius.circular(16),
          boxShadow: [
            BoxShadow(
                color: color.withValues(alpha: .13),
                blurRadius: 8,
                offset: const Offset(0, 4))
          ],
        ),
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 18),
          child: Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(icon, color: Colors.white, size: 22),
                  const SizedBox(width: 8),
                  Text('$number. $title',
                      textAlign: TextAlign.center,
                      style: const TextStyle(
                          color: Colors.white,
                          fontSize: 20,
                          fontWeight: FontWeight.w900)),
                ],
              ),
              const SizedBox(height: 9),
              Text(example,
                  textAlign: TextAlign.center,
                  style: const TextStyle(
                      color: Colors.white,
                      fontSize: 13,
                      height: 1.45)),
            ],
          ),
        ),
      );

  Widget _infoCard(String title, String intro, List<String> bullets) =>
      _expandCard(title, intro, bullets);

  Widget _scenario({
    required String title,
    required String situation,
    required List<String> actions,
  }) =>
      _expandCard(title, 'SCENARIO: $situation', actions);

  Widget _expandCard(String title, String intro, List<String> bullets) =>
      Card(
        margin: const EdgeInsets.only(top: 10),
        elevation: 0,
        color: Colors.white,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(15),
          side: const BorderSide(color: Color(0xFFE1E9E3)),
        ),
        child: ExpansionTile(
          tilePadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 5),
          childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
          iconColor: _green,
          collapsedIconColor: _muted,
          title: Text(title,
              style: const TextStyle(
                  color: _ink, fontWeight: FontWeight.w800, fontSize: 15)),
          children: [
            Align(
              alignment: Alignment.centerLeft,
              child: Text(intro,
                  style: const TextStyle(
                      color: _ink, fontSize: 14, height: 1.55)),
            ),
            const SizedBox(height: 10),
            ...bullets.map((item) => Padding(
                  padding: const EdgeInsets.only(bottom: 8),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Icon(Icons.check_circle,
                          size: 17, color: _green),
                      const SizedBox(width: 9),
                      Expanded(
                        child: Text(item,
                            style: const TextStyle(
                                color: _ink, fontSize: 13.5, height: 1.5)),
                      ),
                    ],
                  ),
                )),
          ],
        ),
      );

  Widget _checklist() => Card(
        margin: const EdgeInsets.only(top: 12),
        elevation: 0,
        color: Colors.white,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(15),
            side: const BorderSide(color: Color(0xFFE1E9E3))),
        child: const _InteractiveChecklist(),
      );

  Widget _toolboxTalk() => _expandCard(
        '17. Toolbox Talk — 5-minute sample',
        'Topic: Proper waste segregation at a construction site. Explain that mixing waste can cause injury, chemical exposure, fire and environmental pollution.',
        [
          'Use only designated waste containers.',
          'Never put used oil, chemical containers or oily absorbents into general waste.',
          'Do not overfill skips; keep access routes clear.',
          'Report damaged, leaking or unidentified containers immediately.',
          'Wear task-appropriate PPE and follow the site waste plan.',
          'Ask the team: “What will you do if you find an unidentified chemical container?” Expected response: do not open or mix it; keep clear, report and request competent identification.',
        ],
      );

  Widget _interviewQuestions() => _expandCard(
        '18. HSE Officer interview — questions and model answers',
        'Use these answers as learning prompts. Align final answers with the current official CoP, employer procedures and project requirements.',
        [
          'Q: What is CoP 54.0? A: ADOSH-SF Code of Practice 54.0 covering Waste Management.',
          'Q: What is segregation? A: Separating waste streams at source according to classification and approved handling route.',
          'Q: What is the waste hierarchy? A: Prevent, reduce, reuse, recycle, recover and dispose as the last option.',
          'Q: What if used oil is found in a general skip? A: Stop further mixing, assess risk, arrange competent safe segregation, verify approved storage/disposal and record corrective action.',
          'Q: What if a waste provider permit cannot be verified? A: Hold the transfer until provider and destination authorization and documents are confirmed.',
          'Q: What are common waste hazards? A: Cuts, slips, chemical exposure, fire, manual handling injury, falling materials and environmental contamination.',
          'Q: What is the HSE Officer role? A: Verify the plan, inspect controls, check records/providers, brief workers, report non-compliance and close corrective actions.',
        ],
      );

  Widget _sourceNote() => Container(
        margin: const EdgeInsets.only(top: 16),
        padding: const EdgeInsets.all(15),
        decoration: BoxDecoration(
          color: const Color(0xFFE8F1EB),
          borderRadius: BorderRadius.circular(14),
          border: Border.all(color: const Color(0xFFC7DCCB)),
        ),
        child: const Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('REGULATORY SOURCE & IMPORTANT NOTE',
                style: TextStyle(
                    color: _deepGreen,
                    fontWeight: FontWeight.w900,
                    fontSize: 13)),
            SizedBox(height: 8),
            Text(
              'ADPHC / ADOSH-SF — Code of Practice 54.0, Waste Management, Version 4.0 (15 July 2024). Verify the latest official issue and authority requirements before site implementation. Practical examples in this handbook are training guidance and do not replace approved project procedures, risk assessment or legal requirements.',
              style: TextStyle(color: _ink, fontSize: 12.5, height: 1.5),
            ),
            SizedBox(height: 8),
            SelectableText(
              'https://www.adphc.gov.ae/en/Legislation/Code-of-Practices',
              style: TextStyle(
                  color: _deepGreen,
                  fontSize: 12,
                  decoration: TextDecoration.underline),
            ),
          ],
        ),
      );
}

class _StatusPill extends StatelessWidget {
  const _StatusPill();

  @override
  Widget build(BuildContext context) => Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
        decoration: BoxDecoration(
          color: Colors.white.withValues(alpha: .18),
          borderRadius: BorderRadius.circular(30),
          border: Border.all(color: Colors.white54),
        ),
        child: const Text('FIELD GUIDE',
            style: TextStyle(
                color: Colors.white,
                fontSize: 10,
                fontWeight: FontWeight.w800)),
      );
}

class _InteractiveChecklist extends StatefulWidget {
  const _InteractiveChecklist();

  @override
  State<_InteractiveChecklist> createState() => _InteractiveChecklistState();
}

class _InteractiveChecklistState extends State<_InteractiveChecklist> {
  final List<String> _items = const [
    'Waste Management Plan available',
    'Waste streams identified and segregated',
    'Suitable labelled bins and skips available',
    'Hazardous waste stored separately',
    'Containers sound, closed and leak-free',
    'Storage area clean, secure and accessible',
    'No uncontrolled spill or drain contamination',
    'Provider and destination approvals verified',
    'Transfer / consignment records available',
    'Workers briefed and trained',
    'Spill kit and emergency arrangements available',
    'Previous corrective actions closed',
  ];
  final Set<int> _done = {};

  @override
  Widget build(BuildContext context) => Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('16. HSE Officer inspection checklist',
                style: TextStyle(
                    color: AbuDhabiCop54Page._ink,
                    fontSize: 16,
                    fontWeight: FontWeight.w900)),
            const SizedBox(height: 5),
            Text('${_done.length} / ${_items.length} checked',
                style: const TextStyle(
                    color: AbuDhabiCop54Page._muted, fontSize: 12)),
            const SizedBox(height: 8),
            ClipRRect(
              borderRadius: BorderRadius.circular(10),
              child: LinearProgressIndicator(
                value: _done.length / _items.length,
                minHeight: 7,
                backgroundColor: const Color(0xFFE4EAE5),
                color: AbuDhabiCop54Page._green,
              ),
            ),
            const SizedBox(height: 8),
            ...List.generate(
              _items.length,
              (i) => CheckboxListTile(
                contentPadding: EdgeInsets.zero,
                dense: true,
                controlAffinity: ListTileControlAffinity.leading,
                activeColor: AbuDhabiCop54Page._green,
                value: _done.contains(i),
                title: Text(_items[i],
                    style: const TextStyle(
                        color: AbuDhabiCop54Page._ink,
                        fontSize: 13,
                        height: 1.35)),
                onChanged: (value) => setState(() {
                  if (value == true) {
                    _done.add(i);
                  } else {
                    _done.remove(i);
                  }
                }),
              ),
            ),
            Align(
              alignment: Alignment.centerRight,
              child: TextButton.icon(
                onPressed: () => setState(_done.clear),
                icon: const Icon(Icons.refresh),
                label: const Text('Reset checklist'),
              ),
            ),
          ],
        ),
      );
}
