name: SafeNexus HSE APK Build

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: '17'
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.2'
          channel: stable
          cache: true

      - name: Check Flutter Version
        run: |
          flutter --version
          dart --version

      - name: Flutter Clean
        run: flutter clean

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze Flutter Project
        run: flutter analyze

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SafeNexus-HSE-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
