import 'dart:io';
import 'package:excel/excel.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class IndustrialDocumentExport {
  static String safe(String s)=>s.replaceAll(RegExp(r'[^A-Za-z0-9_-]+'),'_');
  static Future<void> pdf(Map<String,dynamic> r) async {
    final d=pw.Document(); final fields=Map<String,dynamic>.from(r['fields'] as Map? ?? {});
    d.addPage(pw.MultiPage(build:(_)=>[pw.Header(level:0,child:pw.Text((r['title']??'Industrial HSE Document').toString(),style:pw.TextStyle(fontSize:18,fontWeight:pw.FontWeight.bold))),pw.Text('Document No: ${r['documentNo']??''}    Revision: ${r['revision']??''}    Status: ${r['status']??'Draft'}'),pw.SizedBox(height:12),pw.TableHelper.fromTextArray(data:[['FIELD','RECORDED INFORMATION'],...fields.entries.map((e)=>[e.key,e.value.toString()])]),pw.SizedBox(height:16),pw.Text('Prepared: ${r['preparedBy']??''}'),pw.Text('Reviewed: ${r['reviewedBy']??''}'),pw.Text('Approved: ${r['approvedBy']??''}'),pw.SizedBox(height:12),pw.Text('Revision snapshot: ${r['revision']??'0'} | Generated by SafeNexus HSE',style:const pw.TextStyle(fontSize:8))]));
    await Printing.sharePdf(bytes:await d.save(),filename:'${safe((r['title']??'Industrial_Document').toString())}_${safe((r['documentNo']??'draft').toString())}.pdf');
  }
  static Future<void> excel(Map<String,dynamic> r) async { final b=Excel.createExcel(); final s=b['Industrial Document']; s.appendRow([TextCellValue((r['title']??'Industrial HSE Document').toString())]); s.appendRow([TextCellValue('Field'),TextCellValue('Value')]); final fields=Map<String,dynamic>.from(r['fields'] as Map? ?? {}); for(final e in fields.entries){s.appendRow([TextCellValue(e.key),TextCellValue(e.value.toString())]);} s.appendRow([TextCellValue('Status'),TextCellValue((r['status']??'Draft').toString())]); final bytes=b.encode(); if(bytes==null)return; final dir=await getTemporaryDirectory(); final f=File('${dir.path}/${safe((r['documentNo']??'industrial_draft').toString())}.xlsx'); await f.writeAsBytes(bytes,flush:true); await Share.shareXFiles([XFile(f.path)],text:'Industrial HSE document workbook'); }
  static Future<void> word(Map<String,dynamic> r) async { final fields=Map<String,dynamic>.from(r['fields'] as Map? ?? {}); String esc(String x)=>x.replaceAll('\\','\\\\').replaceAll('{',r'\{').replaceAll('}',r'\}').replaceAll('\n',r'\par '); final body='${r['title']??'Industrial HSE Document'}\nDocument No: ${r['documentNo']??''}\nRevision: ${r['revision']??'0'}\nStatus: ${r['status']??'Draft'}\n\n${fields.entries.map((e)=>'${e.key}: ${e.value}').join('\n')}\n\nPrepared: ${r['preparedBy']??''}\nReviewed: ${r['reviewedBy']??''}\nApproved: ${r['approvedBy']??''}'; final dir=await getTemporaryDirectory(); final f=File('${dir.path}/${safe((r['documentNo']??'industrial_draft').toString())}.rtf'); await f.writeAsString('{\\rtf1\\ansi\\deff0 {\\fonttbl {\\f0 Arial;}}\\f0\\fs22 ${esc(body)}\\par}',flush:true); await Share.shareXFiles([XFile(f.path)],text:'Word-compatible RTF document'); }
}
